// contrib/views/storm-vue/src/main/resources/ui/src/components/CommonExpanded.vue
<template>
  <div class="box-control pull-right box-custom">
    <span class="primary"><i :class="computedClassed"></i></span>
  </div>
</template>
<script>
  export default{
    name : "CommonExpanded",
    props : ["expandedProps"],
    data() {
      return {

      };
    },
    computed : {
      computedClassed(){
        return this.expandedProps ? 'fa fa-compress' : 'fa fa-expand';
      }
    }
  };
</script>
<style scoped>
.box-custom{
  margin-left: 17px;
  margin-top: -2px;
}
</style>

// contrib/views/storm-ui/src/main/resources/ui/app/scripts/components/CommonExpanded.jsx
import React, {Component} from 'react';

const CommonExpanded = (props) => {
  const {expandFlag} = props;
  return (
    <div className="box-control pull-right" style={{marginLeft : '17px',marginTop : '-2px'}}>
      <span className="primary"><i className={`fa ${expandFlag ? 'fa-expand' : 'fa-compress'}`}></i></span>
    </div>
  );
};

export default CommonExpanded;
