// storm-app/src/components/CommonSwitchComponent.vue
<template>
  <div class="switchWrapper" :class="[!!KYC ? 'lagSwitchSetting pull-right' : '']">
    <span class="switchSlider" :class="[ checked ? 'onSlider' : 'offSlider']" @click="switchCallBack">
      <span class="switchItemOn sliderText" :class="[ !!KYC ? 'graphSwitchOn' : '']">{{on}}</span>
      <span class="switchItemMid"></span>
      <span class="switchItemOff sliderText" :class="[ !!KYC ? 'graphSwitchOff' : '']">{{off}}</span>
    </span>
  </div>
</template>
<script>
  export default{
    name : "CommonSwitchComponent",
    props : ["KYC","checked","textON","textOFF"],
    data() {
      return{
        on : !!this.textON ? this.textON : "ON",
        off : !!this.textOFF ? this.textOFF : "OFF"
      };
    },
    methods : {
      switchCallBack(){
        this.$emit('switchCallBack');
      }
    }
  };
</script>

// contrib/views/storm-ui/src/main/resources/ui/app/scripts/components/CommonSwitchComponent.jsx
import React, {Component} from 'react';

export default class CommonSwitchComponent extends Component {
  render(){
    const {switchCallBack,checked,textON,textOFF,KYC} = this.props;
    let switchId = "switch-"+((Math.random())*100).toFixed(0);
    return (
      <div className={`switchWrapper ${!!KYC ? 'lagSwitchSetting pull-right' : ''}`}>
        <span className={`switchSlider ${checked ?  'onSlider' : 'offSlider'}`} onClick={switchCallBack}>
          <span className={`switchItemOn sliderText ${!!KYC ? 'graphSwitchOn' : ''}`}>{textON}</span>
          <span className="switchItemMid"></span>
          <span className={`switchItemOff sliderText ${!!KYC ? 'graphSwitchOff' : ''}`}>{textOFF}</span>
        </span>
      </div>

    );
  }
}

CommonSwitchComponent.defaultProps = {
  textON : "ON",
  textOFF : "OFF"
};
