// storm-app/src/components/LogLevelComponent.vue
<template>
  <div class="boxAnimated">
      <hr/>
      <h4 class="col-sm-offset-5">Change Log Level</h4>
      <p>Modify the logger levels for topology. Note that applying a setting restarts the timer in the workers. To configure the root logger, use the name ROOT.</p>
      <app-CommonTable
        classname='no-margin'
        :items="items"
        :fields="fields"
        :showPagination="showPagination"
        :tableHeaderData="tableHeaderData"
      >
        <template scope="{item}" slot="__logger__">
          <a v-if="!item.item.footer" href="javascript:void(0)">{{item.value}}</a>
          <app-Editable v-else
            ref="addRowRef"
            :inline="true"
            childType="input"
            :defaultValue="selectedKeyName"
            @callBack="handleNameChange"
            @resolve="addLoggerName('addRowRef','save')"
            @reject="addLoggerName('addRowRef','reject')"
          >
          </app-Editable>
        </template>

        <template scope="{item}" slot="__target_level__">
          {{item.value}}
        </template>

        <template scope="{item}" slot="__timeout__">
          <app-Editable
            :ref="item.item.footer ? 'timeoutRef' : item.item.logger+'-'+item.index "
            :inline="true"
            childType="input"
            :defaultValue="item.item.footer ? selectedTimeOut : item.value "
            @callBack="handleTimeChange"
            @resolve="modifyCommonObjValue(item.item.footer ? 'timeoutRef' : item.item.logger+'-'+item.index,item.item.logger,'timeout','save', item.item.footer ? 'ADD' : null)"
            @reject="modifyCommonObjValue(item.item.footer ? 'timeoutRef' : item.item.logger+'-'+item.index,item.item.logger,'timeout','reject', item.item.footer ? 'ADD' : null)"
          >
          </app-Editable>
        </template>

        <template scope="{item}" slot="__timeout_epoch__">
          {{getDateFormat(item.value)}}
        </template>

        <template scope="{item}" slot="__action__">
          <span>
					  <a href="javascript:void(0)" class="btn btn-success btn-xs"
              @click="!item.item.footer ? saveAndClearLogConfig(item.item.logger,'save') : addLogRow('save') " >
              <i class="fa fa-check"></i>
            </a>&nbsp;
					  <a v-if="!item.item.footer"  href="javascript:void(0)" class="btn btn-danger btn-xs" @click="saveAndClearLogConfig(item.item.logger,'clear')"><i class="fa fa-times"></i></a>
					</span>
        </template>

      </app-CommonTable>
  </div>
</template>
<script>
  import TopologyREST from '@/rest/TopologyREST';
  import _ from 'lodash';
  import Editable from '@/components/Editable';
  import FilterUtils from '@/utils/FilterUtils';
  import CommonTable from '@/components/CommonTable';

  export default{
    name : "LogLevelComponent",
    props :["topologyId"],
    components : {
      "app-Editable" : Editable,
      "app-CommonTable" : CommonTable
    },
    data(){
      let tableFields = this.getTableFields();
      return{
        logLevelObj : {},
        traceOption : this.populateTraceOptions(),
        selectedKeyName : 'com.your.organization.LoggerName',
        selectedTrace : 'ALL',
        selectedTimeOut : 30,
        keyName : '',
        timeChange : '',
        fields: tableFields,
        items: [],
        showPagination: false,
        tableHeaderData : [
          {fieldName: "logger", tooltip: "Logger", isCustom: true},
          {fieldName: "target_level", tooltip: "Level", isCustom: true},
          {fieldName: "timeout", tooltip: "Timeout", isCustom: true},
          {fieldName: "timeout_epoch", tooltip: "Expires At",  isCustom: true},
          {fieldName: "action", tooltip: "Action", isCustom: true}
        ]
      };
    },
    created(){
      this.fetchData();
    },
    methods : {
      getTableFields(){
        return {
          logger: {label: 'Logger'},
          target_level: {label: 'Level'},
          timeout: {label: 'Timeout'},
          timeout_epoch: {label: 'Expires At'},
          action: {label: 'Action'}
        };
      },

      fetchData(){
        const {topologyId} = this;
        let self = this;
        TopologyREST.getLogConfig(topologyId).then((result) => {
          if(result.responseMessage !== undefined){
            console.error(result.responseMessage);
          } else {
            self.selectedKeyName = 'com.your.organization.LoggerName';
            self.selectedTrace = 'ALL';
            self.selectedTimeOut = 30;
            self.logLevelObj = result.namedLoggerLevels;
            self.items = this.objectToArray(result.namedLoggerLevels);
          }
        });
      },

      objectToArray(obj){
        const {selectedKeyName,selectedTrace,selectedTimeOut} = this;
        let arr=[];
        const keyList = _.keys(obj);
        _.map(keyList,(key,i) => {
          const o = Object.assign(obj[key],{logger : key});
          arr.push(o);
        });
        const t = {logger : selectedKeyName, reset_level : "DEBUG", target_level : selectedTrace, timeout : selectedTimeOut,footer : true};
        arr.push(t);
        return arr;
      },

      populateTraceOptions(){
        let temp=[];
        const arr = ['ALL','TRACE','DEBUG','INFO','WARN','ERROR','FATAL','OFF'];
        _.map(arr, (a) => {
          temp.push({label : a, value : a});
        });
        return temp;
      },

      handleNameChange(val){
        this.keyName =  val;
      },

      handleTimeChange(val){
        this.timeChange =  val;
      },

      traceLavelChange(type,key,addRow,obj){
        let tempKeyName = 'ALL';
        if(!!addRow){
          tempKeyName = obj.value;
        } else{
          this.logLevelObj[type][key] = obj.value;
        }
        this.selectedTrace = tempKeyName;
      },

      modifyCommonObjValue(refType,type,key,action,addRow){
        if(action === 'save' && addRow === null){
          this.logLevelObj[type][key] = parseInt(this.timeChange,10);
        } else if(action === 'save' && !!addRow){
          this.selectedTimeOut = parseInt(this.timeChange, 10);
        }
        this.$refs[refType].hideEditor();
        this.timeChange = '';
      },

      getDateFormat(str){
        const d = new Date(str);
        return str !== undefined ? d.toLocaleDateString() + ' ' + d.toLocaleTimeString() : '';
      },

      saveAndClearLogConfig(type,action){
        let obj={},namedLoggerLevels={};
        obj.namedLoggerLevels={};
        if(action === 'clear'){
          obj.namedLoggerLevels[type] = {};
          obj.namedLoggerLevels[type].timeout = 0;
          obj.namedLoggerLevels[type].target_level = null;
        } else {
          obj.namedLoggerLevels[type] = this.logLevelObj[type];
        }
        obj.namedLoggerLevels[type].reset_level = 'INFO';
        delete obj.namedLoggerLevels[type].timeout_epoch;

        this.callLogConfigAPI(obj,null,action);
      },

      callLogConfigAPI(obj,addRow,action){
        const {topologyId,logConfig,logLevelObj} =  this;
        TopologyREST.postLogConfig(topologyId, {body : JSON.stringify(obj)}).then((result) => {
          if(result.responseMessage !== undefined){
            this.logLevelObj = logConfig;
            console.error(result.responseMessage);
          } else {
            let msg = !!addRow ? "Log configuration added successfully" : (action === 'save' ? "Log configuration applied successfully." : "Log configuration cleared successfully.");
            console.log(msg);
            this.fetchData();
          }
        });
      },

      addLoggerName(refType,action){
        if(action === 'save'){
          this.selectedKeyName = !!this.keyName ? this.keyName :  this.selectedKeyName;
        }
        this.$refs[refType].hideEditor();
      },

      addLogRow(){
        const {selectedKeyName,selectedTrace,selectedTimeOut} = this;
        let obj={};
        obj.namedLoggerLevels = {};
        obj.namedLoggerLevels[selectedKeyName] = {};
        obj.namedLoggerLevels[selectedKeyName].target_level = selectedTrace;
        obj.namedLoggerLevels[selectedKeyName].reset_level = 'INFO';
        obj.namedLoggerLevels[selectedKeyName].timeout = selectedTimeOut;
        this.callLogConfigAPI(obj,'addRow');
      }

    }
  };
</script>

// contrib/views/storm-ui/src/main/resources/ui/app/scripts/components/LogLevelComponent.jsx
import React, {Component} from 'react';
import TopologyREST from '../rest/TopologyREST';
import {
  Table,
  Thead,
  Th,
  Tr,
  Td,
  unsafe
} from 'reactable';
import CommonPagination from './CommonPagination';
import {toastOpt,pageSize} from '../utils/Constants';
import Select from 'react-select';
import FSReactToastr from './FSReactToastr';
import CommonNotification from './CommonNotification';
import Editable  from './Editable';

export default class LogLevelComponent extends Component{
  constructor(props){
    super(props);
    this.state = {
      logLevelObj : {},
      traceOption : this.populateTraceOptions(),
      selectedKeyName : 'com.your.organization.LoggerName',
      selectedTrace : 'ALL',
      selectedTimeOut : 30
    };
    this.fetchData();
    this.keyName = '';
    this.timeChange='';
  }

  fetchData = () => {
    const {topologyId} = this.props;
    TopologyREST.getLogConfig(topologyId).then((result) => {
      if(result.responseMessage !== undefined){
        FSReactToastr.error(
          <CommonNotification flag="error" content={result.responseMessage}/>, '', toastOpt);
      } else {
        let stateObj={};
        stateObj.selectedKeyName = 'com.your.organization.LoggerName';
        stateObj.selectedTrace = 'ALL';
        stateObj.selectedTimeOut = 30;
        stateObj.logLevelObj = result.namedLoggerLevels;
        this.setState(stateObj);
      }
    });
  }

  populateTraceOptions = () => {
    let temp=[];
    const arr = ['ALL','TRACE','DEBUG','INFO','WARN','ERROR','FATAL','OFF'];
    _.map(arr, (a) => {
      temp.push({label : a, value : a});
    });
    return temp;
  }

  handleNameChange = (e) => {
    this.keyName =  e.target.value.trim();
  }

  handleTimeChange = (e) => {
    this.timeChange =  e.target.value.trim();
  }

  traceLavelChange = (type,key,addRow,obj) => {
    let tempObj = _.cloneDeep(this.state.logLevelObj);
    let tempKeyName = 'ALL';
    if(!!addRow){
      tempKeyName = obj.value;
    } else{
      tempObj[type][key] = obj.value;
    }
    this.setState({logLevelObj : tempObj,selectedTrace : tempKeyName});
  }

  modifyCommonObjValue = (refType,type,key,action,addRow) => {
    let logObj = _.cloneDeep(this.state.logLevelObj);
    let tempTimeOut = _.cloneDeep(this.state.selectedTimeOut);
    if(action === 'save' && addRow === null){
      logObj[type][key] = parseInt(this.timeChange,10);
    } else if(action === 'save' && !!addRow){
      tempTimeOut = parseInt(this.timeChange, 10);
    }
    this.refs[refType].hideEditor();
    this.setState({logLevelObj : logObj ,selectedTimeOut :tempTimeOut }, () => {
      this.timeChange = '';
    });
  }

  getDateFormat = (str) => {
    const d = new Date(str);
		  return d.toLocaleDateString() + ' ' + d.toLocaleTimeString();
  }

  saveAndClearLogConfig = (type,action) => {
    let tempObj = _.cloneDeep(this.state.logLevelObj);
    let obj={},namedLoggerLevels={};
    obj.namedLoggerLevels={};
    if(action === 'clear'){
      obj.namedLoggerLevels[type] = {};
      obj.namedLoggerLevels[type].timeout = 0;
      obj.namedLoggerLevels[type].target_level = null;
    } else {
      obj.namedLoggerLevels[type] = tempObj[type];
    }
    obj.namedLoggerLevels[type].reset_level = 'INFO';
    delete obj.namedLoggerLevels[type].timeout_epoch;

    this.callLogConfigAPI(obj,null,action);
  }

  callLogConfigAPI = (obj,addRow,action) => {
    const {topologyId,logConfig} =  this.props;
    const {logLevelObj} = this.state;
    TopologyREST.postLogConfig(topologyId, {body : JSON.stringify(obj)}).then((result) => {
      if(result.responseMessage !== undefined){
        this.setState({logLevelObj : logConfig});
        FSReactToastr.error(
          <CommonNotification flag="error" content={result.responseMessage}/>, '', toastOpt);
      } else {
        let msg = !!addRow ? "Log configuration added successfully" : (action === 'save' ? "Log configuration applied successfully." : "Log configuration cleared successfully.");
        FSReactToastr.success(<strong>{msg}</strong>);
        this.fetchData();
      }
    });
  }

  addLoggerName = (refType,action) => {
    let tempName = _.cloneDeep(this.state.selectedKeyName);
    if(action === 'save'){
      tempName = !!this.keyName ? this.keyName :  tempName;
    }
    this.refs[refType].hideEditor();
    this.setState({selectedKeyName : tempName});
  }

  addLogRow = () => {
    const {selectedKeyName,selectedTrace,selectedTimeOut} = this.state;
    let obj={};
    obj.namedLoggerLevels = {};
    obj.namedLoggerLevels[selectedKeyName] = {};
    obj.namedLoggerLevels[selectedKeyName].target_level = selectedTrace;
    obj.namedLoggerLevels[selectedKeyName].reset_level = 'INFO';
    obj.namedLoggerLevels[selectedKeyName].timeout = selectedTimeOut;
    this.callLogConfigAPI(obj,'addRow');
  }

  render(){
    const {logLevelObj,traceOption,selectedKeyName,selectedTrace,selectedTimeOut} = this.state;
    return(
      <div className={`boxAnimated`}>
        <hr/>
				<h4 className="col-sm-offset-5">Change Log Level</h4>
				<p>Modify the logger levels for topology. Note that applying a setting restarts the timer in the workers. To configure the root logger, use the name ROOT.</p>
        <Table className="table no-margin">
          <Thead>
            <Th column="logger" title="Logger">Logger</Th>
            <Th column="target_level" title="Level">Level</Th>
            <Th column="timeout" title="Timeout">Timeout</Th>
            <Th column="timeout_epoch" title="Expires At">Expires At</Th>
            <Th column="action" title="Action">Action</Th>
          </Thead>
          {
            _.map(_.keys(logLevelObj), (logKey, i) => {
              return <Tr key={i}>
                      <Td column="logger">
                        <a href="javascript:void(0)">{logKey}</a>
                      </Td>
                      <Td column="target_level">{}
                        <Select value={logLevelObj[logKey].target_level} options={traceOption} onChange={this.traceLavelChange.bind(this,logKey,'target_level',null)} required={true} clearable={false} />
                      </Td>
                      <Td column="timeout">
                        <Editable ref={`logKey${i}`} inline={true} resolve={this.modifyCommonObjValue.bind(this,`logKey${i}`,logKey,'timeout','save',null)} reject={this.modifyCommonObjValue.bind(this,`logKey${i}`,logKey,'timeout','reject',null)}>
                          <input className="form-control input-sm"  ref={this.focusInput} defaultValue={logLevelObj[logKey].timeout} onChange={this.handleTimeChange.bind(this)}/>
                        </Editable>
                      </Td>
                      <Td column="timeout_epoch">{this.getDateFormat(logLevelObj[logKey].timeout_epoch)}</Td>
                      <Td column="action">
                        <span>
            							<a href="javascript:void(0)" className="btn btn-success btn-xs" onClick={this.saveAndClearLogConfig.bind(this,logKey,'save')}><i className="fa fa-check"></i></a>&nbsp;
            							<a href="javascript:void(0)"  className="btn btn-danger btn-xs" onClick={this.saveAndClearLogConfig.bind(this,logKey,'clear')}><i className="fa fa-times"></i></a>
            							</span>
                      </Td>
                    </Tr>;
            })
          }
          <Tr key={Math.random()}>
            <Td  column="logger">
              <Editable ref="addRowRef" inline={true} resolve={this.addLoggerName.bind(this,'addRowRef','save')} reject={this.addLoggerName.bind(this,"addRowRef",'reject')}>
                <input className="form-control input-sm"  ref={this.focusInput} defaultValue={selectedKeyName} onChange={this.handleNameChange.bind(this)}/>
              </Editable>
            </Td>
            <Td  column="target_level">
              <Select value={selectedTrace} options={traceOption} onChange={this.traceLavelChange.bind(this,null,'target_level','ADD')} required={true} clearable={false} />
            </Td>
            <Td  column="timeout">
              <Editable ref={"timeoutRef"} inline={true} resolve={this.modifyCommonObjValue.bind(this,"timeoutRef",null,'timeout','save','ADD')} reject={this.modifyCommonObjValue.bind(this,"timeoutRef",null,'timeout','reject','ADD')}>
                <input className="form-control input-sm"  ref={this.focusInput} defaultValue={selectedTimeOut} onChange={this.handleTimeChange.bind(this)}/>
              </Editable>
            </Td>
            <Td  column="timeout_epoch">&nbsp;</Td>
              <Td column="action">
                <span>
                  <a href="javascript:void(0)" className="btn btn-primary btn-xs" onClick={this.addLogRow.bind(this,'save')}><i className="fa fa-check"></i></a>&nbsp;
                  </span>
              </Td>
          </Tr>
        </Table>
      </div>
    );
  }
}
