// contrib/views/storm-vue/src/main/resources/ui/src/components/RebalanceTopology.vue
<template>
  <div>
    <div class="form-group row">
      <div class="col-sm-3">
        <label>Workers:<span class="text-danger">*</span></label>
      </div>
      <div class="col-sm-7">
        <span :style="{float : 'left'}">0</span>
        <input type="range" :value="rebalanceData.workers" :min="0" :title="rebalanceData.workers +' workers selected.'" :max="totalWorker" @input="rebalanceValueChange('workers',$event)" :style="{width : '90%', float : 'left',margin : '6px 7px'}" />
        <span :style="{float : 'left', clear : 'right'}">{{totalWorker}}</span>
      </div>
    </div>
    <div class="form-group row" v-for="spout in spoutArr" :key="spout.spoutId">
      <div class="col-sm-3">
        <label>{{spout.spoutId}}:<span class="text-danger">*</span></label>
      </div>
      <div class="col-sm-7">
        <input type="number" class="form-control" :min="0" :value="spout.executors" @input="rebalanceValueChange(spout.spoutId,$event)" />
      </div>
    </div>
    <div class="form-group row" v-for="bolt in boltArr" :key="bolt.boltId">
      <div class="col-sm-3">
        <label>{{bolt.boltId}}:<span class="text-danger">*</span></label>
      </div>
      <div class="col-sm-7">
        <input type="number" class="form-control" :min="0" :value="bolt.executors" @input="rebalanceValueChange(bolt.boltId,$event)" />
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-3">
        <label>Wait Time:<span class="text-danger">*</span></label>
      </div>
      <div class="col-sm-7">
        <input type="number" class="form-control" :min="0" :value="waitTime" @input="waitTimeChange($event)" />
      </div>
    </div>
  </div>
</template>
<script>
  import TopologyREST from '@/rest/TopologyREST';
  import _ from 'lodash';
  import FSToaster from '@/utils/FSToaster';

  export default{
    name : "REBALANCING",
    props : ["topologyId","spoutArr","boltArr","topologyExecutors"],
    data(){
      return{
        freeSlot : 0,
        waitTime : 30,
        rebalanceData : {},
        totalWorker : 0
      };
    },
    created(){
      this.fetchData();
    },
    methods : {
      fetchData(){
        const {topologyExecutors,spoutArr,boltArr} = this;
        let self = this;
        TopologyREST.getSummary('cluster').then((result) => {
          if(result.responseMessage !== undefined){
            FSToaster.error(result.responseMessage);
          } else {
            self.freeSlot = result.slotsFree;
            self.rebalanceData={};
            self.rebalanceData.workers = topologyExecutors + self.freeSlot;
            self.totalWorker = self.rebalanceData.workers;
            _.map(spoutArr, (s) => {
              self.rebalanceData[s.spoutId] = s.executors;
            });
            _.map(boltArr, (b) => {
              self.rebalanceData[b.boltId] = b.executors;
            });
          }
        });
      },

      rebalanceValueChange(type,event){
        this.rebalanceData[type] = +event.target.value;
      },

      waitTimeChange(event){
        this.waitTime = +event.target.value;
      },

      validateData(){
        const {rebalanceData,waitTime} = this;
        let errorFlag = [];
        _.map(_.keys(rebalanceData), (key) => {
          if(rebalanceData[key] === ''){
            errorFlag.push(false);
          }
        });
        if(waitTime === ''){
          errorFlag.push(false);
        }
        return errorFlag.length ? false : true;
      },

      handleSave(){
        const {rebalanceData,waitTime,topologyId} = this;
        let finalData = {
          "rebalanceOptions": {
            "executors": {}
          }
        };
        _.map(_.keys(rebalanceData), (key) => {
          if(key === "workers"){
            finalData.rebalanceOptions.numWorkers = rebalanceData[key];
          } else {
            finalData.rebalanceOptions.executors[key] = rebalanceData[key];
          }
        });

        return TopologyREST.postActionOnTopology(topologyId,'rebalance',waitTime,{body : JSON.stringify(finalData)});
      }



    }
  };
</script>

// contrib/views/storm-ui/src/main/resources/ui/app/scripts/components/RebalanceTopology.jsx
import React, {Component} from 'react';
import TopologyREST from '../rest/TopologyREST';
import {toastOpt,pageSize} from '../utils/Constants';
import Utils from '../utils/Utils';
import FSReactToastr from './FSReactToastr';
import CommonNotification from './CommonNotification';
import _  from 'lodash';

export default class RebalanceTopology extends Component{
  constructor(props){
    super(props);
    this.state = {
      freeSlot : 0,
      waitTime : 30,
      rebalanceData : {}
    };
    this.fetchData();
  }

  fetchData = () => {
    const {topologyExecutors,spoutArr,boltArr} = this.props;
    TopologyREST.getSummary('cluster').then((result) => {
      if(result.responseMessage !== undefined){
        FSReactToastr.error(
          <CommonNotification flag="error" content={result.responseMessage}/>, '', toastOpt);
      } else {
        let stateObj = {};
        stateObj.freeSlot = result.slotsFree;
        stateObj.rebalanceData={};
        stateObj.rebalanceData.workers = topologyExecutors + stateObj.freeSlot;
        this.totalWorker = stateObj.rebalanceData.workers;
        _.map(spoutArr, (s) => {
          stateObj.rebalanceData[s.spoutId] = s.executors;
        });
        _.map(boltArr, (b) => {
          stateObj.rebalanceData[b.boltId] = b.executors;
        });
        this.setState(stateObj);
      }
    });
  }

  rebalanceValueChange = (type,e) => {
    let data = _.cloneDeep(this.state.rebalanceData);
    data[type] = +e.target.value;
    this.setState({rebalanceData : data});
  }

  waitTimeChange = (e) => {
    this.setState({waitTime : +e.target.value});
  }

  validateData = () => {
    const {rebalanceData,waitTime} = this.state;
    let errorFlag = [];
    _.map(_.keys(rebalanceData), (key) => {
      if(rebalanceData[key] === ''){
        errorFlag.push(false);
      }
    });
    if(waitTime === ''){
      errorFlag.push(false);
    }
    return errorFlag.length ? false : true;
  }

  handleSave = () => {
    const {rebalanceData,waitTime} = this.state;
    const {topologyId} = this.props;
    let finalData = {
  			"rebalanceOptions": {
  				"executors": {}
  			}
    };
    _.map(_.keys(rebalanceData), (key) => {
      if(key === "workers"){
        finalData.rebalanceOptions.numWorkers = rebalanceData[key];
      } else {
        finalData.rebalanceOptions.executors[key] = rebalanceData[key];
      }
    });

    return TopologyREST.postActionOnTopology(topologyId,'rebalance',waitTime,{body : JSON.stringify(finalData)});
  }

  render(){
    const {freeSlot,waitTime,rebalanceData} = this.state;
    const {spoutArr,boltArr}= this.props;
    return(
      <div>
        <div className="form-group row">
          <div className="col-sm-3">
            <label>Workers:<span className="text-danger">*</span></label>
          </div>
          <div className="col-sm-7">
            <span style={{float : 'left'}}>0</span><input type="range" title={rebalanceData.workers +' workers selected.'} min={0} style={{width : '90%', float : 'left',margin : '6px 7px' }} max={this.totalWorker} onChange={this.rebalanceValueChange.bind(this,'workers')} /><span style={{float : 'left', clear : 'right'}}>{this.totalWorker}</span>
          </div>
        </div>
        {
          _.map(spoutArr, (s , i) => {
            return  <div className="form-group row" key={i}>
                      <div className="col-sm-3">
                        <label>{s.spoutId}:<span className="text-danger">*</span></label>
                      </div>
                      <div className="col-sm-7">
                        <input type="number" className="form-control" min={0} defaultValue={s.executors} onChange={this.rebalanceValueChange.bind(this,s.spoutId)} />
                      </div>
                    </div>;
          })
        }
        {
          _.map(boltArr, (b , n) => {
            return  <div className="form-group row" key={n}>
                      <div className="col-sm-3">
                        <label>{b.boltId}:<span className="text-danger">*</span></label>
                      </div>
                      <div className="col-sm-7">
                        <input type="number" className="form-control" min={0} defaultValue={b.executors} onChange={this.rebalanceValueChange.bind(this,b.boltId)} />
                      </div>
                    </div>;
          })
        }
        <div className="form-group row">
          <div className="col-sm-3">
            <label>Wait Time:<span className="text-danger">*</span></label>
          </div>
          <div className="col-sm-7">
            <input type="number" className="form-control" min={0} value={waitTime} onChange={this.waitTimeChange.bind(this)} />
          </div>
        </div>
      </div>
    );
  }
}
