// contrib/views/storm-vue/src/main/resources/ui/src/components/SearchLogs.vue
<template>
  <div class="col-md-3 pull-right searchbar" :style="{'margin-bottom' : '10px'}">
    <div class="input-group">
      <input type="text" id="searchBox" class="form-control" placeholder="Search in Logs"/>
      <div class="input-group-btn">
        <div class="btn-group" role="group">
          <div class="dropdown dropdown-lg">
            <b-dropdown id="bg-nested-dropdown" variant="default" right>
              <div>
                <input type="checkbox" id="searchArchivedLogs"  value="accepted" unchecked-value="not_accepted"/>
                <label for="searchArchivedLogs">Search archived logs</label>
              </div>
              <div>
                <input type="checkbox" id="deepSearch"  value="accepted" unchecked-value="not_accepted"/>
                <label for="deepSearch">Deep search</label>
              </div>
           </b-dropdown>
          </div>
          <button type="button" class="btn btn-default" @click="handleSearch">
            <i class="fa fa-search"></i>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
  import {baseUrl} from '@/utils/Constants';

  export default{
    name : "SearchLogs",
    props : ["topologyId"],
    data(){
      return{};
    },
    methods : {
      handleSearch(){
        var searchBoxEl = document.getElementById('searchBox');
        var searchArchivedLogsEl = document.getElementById('searchArchivedLogs');
        var deepSearchEl = document.getElementById('deepSearch');
        var topologyId = this.topologyId;

        fetch(baseUrl.replace('proxy?url=/api/v1/', 'storm_details'), {"credentials": "same-origin"})
          .then((response) => {
            return response.json();
          })
          .then((response) => {
            var url = response.hostdata+'/';
            if(deepSearchEl.checked == true){
              url += "deep_search_result.html";
            }else{
              url += "search_result.html";
            }
            url += '?search='+searchBoxEl.value+'&id='+ topologyId +'&count=1';
            if(searchArchivedLogsEl.checked == true){
              if(deepSearchEl.checked == true){
                url += "&search-archived=on";
              }else{
                url += "&searchArchived=checked";
              }
            }
            window.open(url, '_blank');

            searchBoxEl.value = '';
            searchArchivedLogsEl.checked = false;
            deepSearchEl.checked = false;
          });
      }
    }
  };
</script>
<style scoped>
.custom-control{
    display: block;
}
.custom-control-indicator{
  top: 4px;
  width: 12px;
  height: 12px;
  border: 1px solid #a2a2a2;
}
.searchbar label{
  font-weight: 600;
  color: #4b4b4b;
  cursor: pointer;
}

.searchbar .custom-checkbox .custom-control-input:checked ~ .custom-control-indicator{
  background-color: #dedede;
}

.searchbar .dropdown-menu input[type="checkbox"]{
  margin-right: 3px;
}
.searchbar .dropdown-toggle::after{
  margin-left: 0;
}
.dropdown-toggle::after{
  margin-left: 0 !important;
}

</style>

// contrib/views/storm-ui/src/main/resources/ui/app/scripts/components/SearchLogs.jsx
/**
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership.  The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License.  You may obtain a copy of the License at
*
     http://www.apache.org/licenses/LICENSE-2.0
*
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

import React, {Component} from 'react';
import ReactDOM from 'react-dom';
import {baseUrl} from '../utils/Constants';

export default class SearchLogs extends Component{
  render() {
    return (
      <div className="col-md-3 pull-right searchbar">
        <div className="input-group">
          <input type="text" id="searchBox" className="form-control" placeholder="Search in Logs"/>
          <div className="input-group-btn">
            <div className="btn-group" role="group">
              <div className="dropdown dropdown-lg">
                <button type="button" className="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <span className="caret"></span>
                </button>
                <div className="dropdown-menu dropdown-menu-right" role="menu">
                  <form>
                    <div>
                      <label><input type="checkbox" id="searchArchivedLogs"/> Search archived logs</label>
                    </div>
                    <div>
                      <label><input type="checkbox" id="deepSearch"/> Deep Search</label>
                    </div>
                  </form>
                </div>
              </div>
              <button type="button" className="btn btn-default" onClick={this.handleSearch.bind(this)}>
                <i className="fa fa-search"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }
  handleSearch(){
    var searchBoxEl = document.getElementById('searchBox');
    var searchArchivedLogsEl = document.getElementById('searchArchivedLogs');
    var deepSearchEl = document.getElementById('deepSearch');
    var topologyId = this.props.id;

    fetch(baseUrl.replace('proxy?url=', 'storm_details'))
      .then((response) => {
        return response.json();
      })
      .then((response) => {
        var url = response.hostdata+'/';
        if(deepSearchEl.checked == true){
          url += "deep_search_result.html";
        }else{
          url += "search_result.html";
        }
        url += '?search='+searchBoxEl.value+'&id='+ topologyId +'&count=1';
        if(searchArchivedLogsEl.checked == true){
          if(deepSearchEl.checked == true){
            url += "&search-archived=on";
          }else{
            url += "&searchArchived=checked";
          }
        }
        window.open(url, '_blank');

        searchBoxEl.value = '';
        searchArchivedLogsEl.checked = false;
        deepSearchEl.checked = false;
      });
  }
}
