// contrib/views/storm-ui/src/main/resources/app/scripts/containers/NimbusConfigSummary.jsx
import React, {Component} from 'react';
import _ from 'lodash';
import {
  Table,
  Thead,
  Th,
  Tr,
  Td,
  unsafe
} from 'reactable';
import FSReactToastr from '../components/FSReactToastr';
import {toastOpt} from '../utils/Constants';
import TopologyREST from '../rest/TopologyREST';

export default class NimbusConfigSummary extends Component{
  constructor(props){
    super(props);
    this.fetchData();
    this.state = {
      entity : [],
      collapse : true
    };
  }

  fetchData = () => {
    TopologyREST.getClusterConfig().then((result) => {
      if(result.responseMessage !== undefined){
        FSReactToastr.error(
          <CommonNotification flag="error" content={result.responseMessage}/>, '', toastOpt);
      } else {
        this.setState({entity : result});
      }
    });
  }

  handleFilter = () => {
    console.log('handleFilter');
  }

  handleCollapseClick = (e) => {
    this.setState({collapse : !this.state.collapse});
  }

  render(){
    const {entity,collapse} = this.state;
    return(
      <div className="box node-accordian">
        <div className={`box-header ${collapse ? 'collapsed' : ''}`}  data-toggle="collapse" data-target="#collapseBody" aria-expanded={`${collapse ? false : true}`} aria-controls="collapseBody" onClick={this.handleCollapseClick.bind(this)}>
          <h4>Nimbus Configuration</h4>
          <div className="box-control">
            <a href="javascript:void(0);" className="primary"><i className="fa fa-expand" id="collapseTable"></i></a>
          </div>
        </div>
        <div className={`box-body collapse ${collapse ? '' : 'in'}`} aria-expanded={`${collapse ? false : true}`}>
          <div className="input-group col-sm-4">
            <input type="text"  onKeyUp={this.handleFilter.bind(this)}  className="form-control" placeholder="Search By Key" />
            <span className="input-group-btn">
              <button className="btn btn-primary" type="button"><i className="fa fa-search"></i></button>
            </span>
          </div>
          <Table className="table no-margin"  noDataText="No nimbus configuration found !"  currentPage={0}>
            <Thead>
              <Th column="Key">Key</Th>
              <Th column="value">Value</Th>
            </Thead>
            {
              _.map(_.keys(entity), (k,i) => {
                return(
                  <Tr key={i}>
                    <Td column="Key">{k}</Td>
                    <Td column="value">{entity[k]}</Td>
                  </Tr>
                );
              })
            }
          </Table>
        </div>
      </div>
    );
  }
}

// storm-app/src/containers/NimbusConfigSummary.vue
<template>
    <dashboard-ToggleComponent :caption="title">
      <div class="box-body">
        <div class="input-group col-sm-4">
          <b-form-input v-model="filter" type="text" placeholder="Search By Topology Name"></b-form-input>
          <span class="input-group-btn">
            <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
          </span>
        </div>
        <CommonTable
          classname='no-margin'
          :items="items"
          :fields="fields"
          :showPagination="showPagination"
          :tableHeaderData="tableHeaderData"
        >
        </CommonTable>
      </div>

    </dashboard-ToggleComponent>
</template>

<script>
  import ToggleComponent from '@/components/ToggleComponent';
  import TopologyREST from '@/rest/TopologyREST';
  import CommonTable from '@/components/CommonTable';
  import FilterUtils from '@/utils/FilterUtils';

  export default{
    name: 'NimbusConfigSummary',
    components : {
      "dashboard-ToggleComponent" : ToggleComponent,
      'CommonTable': CommonTable
    },
    data(){
      let tableFields = this.getTableFields();
      return{
        title : "Nimbus Configuration",
        entity : {},
        fields: tableFields,
        nimbusEntities: [],
        items: [],
        filter: null,
        showPagination: true,
        tableHeaderData : [
          {fieldName: "key", tooltip: "Key"},
          {fieldName: "value", tooltip: "Value"}
        ]
      };
    },
    created(){
      this.fetchData();
    },
    methods : {
      getTableFields(){
        return {
          key: {label: 'Key'},
          value: {label: 'Value'}
        };
      },
      // data interpolation from object to arr[]
      dataInterpolation(){
        let arr=[] , self = this;
        Object.keys(this.entity).map((k) =>{
          const obj={};
          obj.key = k;
          obj.value = self.entity[k];
          arr.push(obj);
        });
        this.nimbusEntities = arr;
        this.items = arr;
      },
      // fetchData
      fetchData(){
        TopologyREST.getClusterConfig().then((result) => {
          if(result.responseMessage !== undefined){
            console.error("Error in NimbusConfigSummary");
          } else {
            this.entity = result;
          }
        });
      },
      //Filter by topology name
      onFilter(filterStr){
        if(typeof filterStr === 'string'){
          this.items = this.$options.filters.filterByKey(this.nimbusEntities, filterStr,'key');
        } else {
          return this.items;
        }
      }
    },
    filters: {
      filterByKey: FilterUtils.filterByKey
    },
    watch : {
      entity : function(){
        this.dataInterpolation();
      },
      //when filter value changes, it will call this method; being reactive
      filter(filterStr){
        this.onFilter(filterStr);
      },
      //if no data present in search result, hide pagination
      items(data){
        this.showPagination = data.length > 0;
      }
    }
  };
</script>
