// storm-app/src/containers/SupervisorSummary.vue
<template>
  <div class="row">
    <div class="col-sm-12">
      <div class="box">
        <div class="box-header">
          <h4>Supervisor Summary</h4>
          <div v-if="fromDashboard" class="box-control">
            <router-link to="/supervisor" class="primary"><i class="fa fa-external-link"></i></router-link>
          </div>
        </div>
        <div :class="[{paddless: fromDashboard}, 'box-body']">
          <div v-if="!fromDashboard" class="input-group col-sm-4">
            <b-form-input v-model="filter" type="text" placeholder="Search By Host"></b-form-input>
            <span class="input-group-btn">
              <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
            </span>
          </div>
          <CommonTable
            classname='no-margin'
            :items="items"
            :fields="fields"
            :showPagination="showPagination"
            :tableHeaderData="tableHeaderData"
          >
            <!-- Custom formatted value cells -->
            <template slot="__hostName__" scope="{item}">
              <a :href="item.item.logLink" target="_blank">{{item.item.host}}</a>
            </template>
            <template slot="__slots__" scope="{item}">
              <app-supervisorsummary-radial
                :graphData="[item.item.slotsUsed,item.item.slotsTotal]"
                :labels="labels" :width="width" :height="height"
                :innerRadius="innerRadius"
                :outerRadius="outerRadius" :color="color"></app-supervisorsummary-radial>
            </template>
            <template slot="__cpu__" scope="{item}">
              <app-supervisorsummary-radial
                :graphData="[item.item.usedCpu,item.item.totalCpu]"
                :labels="labels" :width="width" :height="height"
                :innerRadius="innerRadius"
                :outerRadius="outerRadius" :color="color"></app-supervisorsummary-radial>
            </template>
            <template slot="__memory__" scope="{item}">
              <app-supervisorsummary-radial
                :graphData="[item.item.usedMem,item.item.totalMem]"
                :labels="labels" :width="width" :height="height"
                :innerRadius="innerRadius"
                :outerRadius="outerRadius" :color="color"></app-supervisorsummary-radial>
            </template>
            <template scope="{item}" slot="__uptime__">
              <small>{{item.value}}</small>
            </template>
          </CommonTable>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import TopologyREST from '@/rest/TopologyREST';
  import FilterUtils from '@/utils/FilterUtils';
  import RadialChart from '@/components/RadialChart';
  import CommonTable from '@/components/CommonTable';

  export default {
    name: 'SupervisorSummary',
    props: ["fromDashboard"],
    created(){
      this.fetchData();
    },

    data() {
      let tableFields = this.getTableFields();
      return {
        tableHeaderData:[
          {fieldName: "hostName", tooltip: "The hostname reported by the remote host. (Note that this hostname is not the result of a reverse lookup at the Nimbus node.)", isCustom: true},
          {fieldName: "slots", tooltip: "Slots are Workers (processes).", isCustom: true},
          {fieldName: "cpu", tooltip: "CPU that has been allocated.", isCustom: true},
          {fieldName: "memory", tooltip: "Memory that has been allocated.", isCustom: true},
          {fieldName: "uptime", tooltip: "The length of time a Supervisor has been registered to the cluster.", isCustom: true}
        ],
        fields: tableFields,
        entities: [],
        items: [],
        filter: null,
        labels : ['Used','Total'],
        width : null,
        height : null,
        innerRadius :19,
        outerRadius : 21,
        color: ["#bcbcbc", "#235693"],
        showPagination: !this.fromDashboard ? true : false
      };
    },

    methods: {
      //Get all the table fields
      getTableFields(){
        let fields = {
          hostName: {label: 'Host'},
          slots: {label: 'Slots'},
          cpu: {label: 'CPU'},
          memory: {label: 'Memory'},
          uptime: {label: 'Uptime'}
        };
        return fields;
      },

      //Request call to get nimbus data
      fetchData(){
        TopologyREST.getSummary('supervisor').then((result) => {
          if(result.responseMessage !== undefined){
            console.error("Error in SupervisorSummary");
          } else {
            this.entities = result.supervisors;
            this.items = result.supervisors;
          }
        });
      },

      onFilter(filterStr){
        if(typeof filterStr === 'string'){
          this.items = this.$options.filters.filterByKey(this.entities, filterStr, 'host');
        } else {
          return this.items;
        }
      }

    },
    components : {
      'app-supervisorsummary-radial' : RadialChart,
      'CommonTable': CommonTable
    },
    filters: {
      filterByKey: FilterUtils.filterByKey,
      statusClass: FilterUtils.statusClass
    },
    watch:{
      filter(filterStr){
        this.onFilter(filterStr);
      }
    }
  };
</script>

// contrib/views/storm-ui/src/main/resources/app/scripts/containers/SupervisorSummary.jsx
import React, {Component} from 'react';
import _ from 'lodash';
import {
  Table,
  Thead,
  Th,
  Tr,
  Td,
  unsafe
} from 'reactable';
import RadialChart  from '../components/RadialChart';
import FSReactToastr from '../components/FSReactToastr';
import {toastOpt} from '../utils/Constants';
import TopologyREST from '../rest/TopologyREST';
import CommonNotification from '../components/CommonNotification';

export default class SupervisorSummary extends Component{
  constructor(props){
    super(props);
    this.fetchData();
    this.state = {
      entities : []
    };
  }

  fetchData = () => {
    TopologyREST.getSummary('supervisor').then((results) => {
      if(results.responseMessage !== undefined){
        FSReactToastr.error(
          <CommonNotification flag="error" content={results.responseMessage}/>, '', toastOpt);
      } else {
        this.setState({entities : results.supervisors});
      }
    });
  }

  render(){
    const {entities} = this.state;
    return(
      <div>
        <div className="box">
            <div className="box-header">
                <h4>Supervisor Summary</h4>
                <div className="box-control">
                    <a className="primary" href="#!/supervisor"><i className="fa fa-external-link"></i></a>
                </div>
            </div>
            <div className="box-body paddless">
              <Table className="table no-margin supervisor-table" noDataText="No records found." currentPage={0} >
                <Thead>
                  <Th column="host"  title="The hostname reported by the remote host. (Note that this hostname is not the result of a reverse lookup at the Nimbus node.)">Host</Th>
                  <Th column="slots" title="Slots are Workers (processes).">Slots</Th>
                  <Th column="cpu" title="CPU that has been allocated.">CPU</Th>
                  <Th column="memory" title="Memory that has been allocated.">Memory</Th>
                  <Th column="uptime" title="The length of time a Supervisor has been registered to the cluster.">Uptime</Th>
                </Thead>
                {
                  _.map(entities, (entity, i) => {
                    return (
                      <Tr key={i}>
                        <Td column="host"><a href={"#!/supervisor/"+entity.logLink}>{entity.host}</a></Td>
                        <Td column="slots">
                          <RadialChart
                            data={[entity.slotsUsed,entity.slotsTotal]}
                            labels={['Used','Total']}
                            innerRadius={19}
                            outerRadius={21}
                            color={["#bcbcbc", "#235693"]}
                          />
                        </Td>
                        <Td column="cpu">
                          <RadialChart
                            data={[entity.usedCpu,entity.totalCpu]}
                            labels={['Used','Total']}
                            innerRadius={19}
                            outerRadius={21}
                            color={["#bcbcbc", "#235693"]}
                          />
                        </Td>
                        <Td column="memory">
                          <RadialChart
                            data={[entity.usedMem,entity.totalMem]}
                            labels={['Used','Total']}
                            innerRadius={19}
                            outerRadius={21}
                            color={["#bcbcbc", "#235693"]}
                          />
                        </Td>
                        <Td column="uptime"><small>{entity.uptime}</small></Td>
                      </Tr>
                    );
                  })
                }
              </Table>
            </div>
        </div>
      </div>
    );
  }
}
