// contrib/views/storm-ui/src/main/resources/ui/app/scripts/containers/TopologyListing.jsx
import React, {Component} from 'react';
import _ from 'lodash';
import {
  Table,
  Thead,
  Th,
  Tr,
  Td,
  unsafe
} from 'reactable';
import FSReactToastr from '../components/FSReactToastr';
import {toastOpt} from '../utils/Constants';
import TopologyREST from '../rest/TopologyREST';
import CommonNotification from '../components/CommonNotification';
import {Link} from 'react-router';
import {OverlayTrigger, Tooltip} from 'react-bootstrap';
import Breadcrumbs from '../components/Breadcrumbs';
import CommonPagination from '../components/CommonPagination';
import {pageSize} from '../utils/Constants';
import Utils from '../utils/Utils';

export default class TopologyListing extends Component{
  constructor(props){
    super(props);
    this.fetchData();
    this.state = {
      entities : [],
      filterValue: '',
      activePage: 1
    };
  }

  fetchData = () => {
    TopologyREST.getSummary('topology').then((results) => {
      if(results.responseMessage !== undefined){
        FSReactToastr.error(
          <CommonNotification flag="error" content={results.responseMessage}/>, '', toastOpt);
      } else {
        let stateObj={};
        stateObj.entities = results.topologies;
        if(!this.props.fromDashboard){
          var additionalColumns = [
            {name: 'assignedTotalMem', title: 'Memory Assigned (MB)', tooltip:'Assigned Total Memory by Scheduler.'},
            {name: 'workersTotal', title: 'Workers', tooltip:'The number of Workers (processes).'},
            {name: 'executorsTotal', title: 'Executors', tooltip:'Executors are threads in a Worker process.'},
            {name: 'tasksTotal', title: 'Tasks', tooltip:'A Task is an instance of a Bolt or Spout. The number of Tasks is almost always equal to the number of Executors.'},
            {name: 'owner', title: 'Owner', tooltip:'The user that submitted the Topology, if authentication is enabled.'}
          ];
          Array.prototype.push.apply(stateObj.entities, additionalColumns);
        }
        this.setState({entities : stateObj.entities});
      }
    });
  }

  getLinks(){
    var links = [
      {link: '#/', title: 'Dashboard'},
      {link: '#/topology', title: 'Topology Listing'}
    ];
    return links;
  }

  activeClass = (status) => {
    let classname="label ";
    switch(status){
    case 'ACTIVE':
      classname += "label-success";
      break;
    case 'INACTIVE':
      classname += "label-default";
      break;
    case 'REBALANCING':
      classname += "label-warning";
      break;
    case 'KILLED':
      classname += "label-danger";
      break;
    default:
      classname += "label-primary";
      break;
    }
    return classname;
  }

  handleFilter = (e) => {
    this.setState({filterValue: e.target.value.trim()});
  }

  callBackFunction = (eventKey) => {
    this.setState({activePage : eventKey});
  }

  render(){
    const {entities, filterValue, activePage} = this.state;
    const {fromDashboard} = this.props;
    const topologies = _.filter(entities, (e)=>{return e.id !== undefined;});
    const filteredEntities = Utils.filterByKey(topologies, filterValue, 'name');
    const paginationObj = {
      activePage,
      pageSize,
      filteredEntities
    };
    return(
      <div className={fromDashboard ? "" : "container-fluid"}>
        {!fromDashboard ? <Breadcrumbs links={this.getLinks()} /> : ''}
        <div className="box">
            <div className="box-header">
                <h4>Topology Listing</h4>
                {fromDashboard ?
                <div className="box-control">
                    <a className="primary" href="#/topology"><i className="fa fa-external-link"></i></a>
                </div>
                : ''}
            </div>
            <div className={fromDashboard ? "box-body paddless" : "box-body"}>
              {!fromDashboard ?
              <div className="input-group col-sm-4">
                <input type="text" onKeyUp={this.handleFilter} className="form-control" placeholder="Search By Topology Name" />
                <span className="input-group-btn">
                <button className="btn btn-primary" type="button"><i className="fa fa-search"></i></button>
                </span>
              </div>
              : ''}
              <Table className="table topology-table" noDataText="No topology found." currentPage={0} >
                <Thead>
                  <Th column="topologyName"><OverlayTrigger placement="bottom" overlay={<Tooltip id="tooltip1">The name given to the topology by when it was submitted. Click the name to view the Topology's information.</Tooltip>}><span>Topology Name</span></OverlayTrigger></Th>
                  <Th column="status"><OverlayTrigger placement="bottom" overlay={<Tooltip id="tooltip1">The status can be one of ACTIVE, INACTIVE, KILLED, or REBALANCING.</Tooltip>}><span>Status</span></OverlayTrigger></Th>
                  {
                    !fromDashboard
                    ? [
                      <Th key={3} column="assignedTotalMem" title="Assigned Total Memory by Scheduler.">Memory Assigned (MB)</Th>,
                      <Th key={4} column="workersTotal" title="The number of Workers (processes).">Workers</Th>,
                      <Th key={5} column="executorsTotal" title="Executors are threads in a Worker process.">Executors</Th>,
                      <Th key={6} column="tasksTotal" title="A Task is an instance of a Bolt or Spout. The number of Tasks is almost always equal to the number of Executors.">Tasks</Th>,
                      <Th key={7} column="owner" title="The user that submitted the Topology, if authentication is enabled.">Owner</Th>,
                      <Th key={8} column="uptime" title="The time since the Topology was submitted.">Uptime</Th>
                    ]
                    : <Th column="uptime"><OverlayTrigger placement="bottom" overlay={<Tooltip id="tooltip1">The time since the Topology was submitted.</Tooltip>}><span>Uptime</span></OverlayTrigger></Th>
                  }
                </Thead>
                {
                  _.map(filteredEntities, (entity, i) => {
                    return (
                      <Tr key={i}>
                        <Td column="topologyName"><Link to={"topology/"+entity.id}>{entity.name}</Link></Td>
                        <Td column="status"><span className={this.activeClass(entity.status)}>{entity.status}</span></Td>
                        {
                          !fromDashboard
                          ? [
                            <Td key={i+'assignedTotalMem'} column="assignedTotalMem">{entity.assignedTotalMem}</Td>,
                            <Td key={i+'workersTotal'} column="workersTotal">{entity.workersTotal}</Td>,
                            <Td key={i+'executorsTotal'} column="executorsTotal">{entity.executorsTotal}</Td>,
                            <Td key={i+'tasksTotal'} column="tasksTotal">{entity.tasksTotal}</Td>,
                            <Td key={i+'owner'} column="owner">{entity.owner}</Td>
                          ]
                          : ''
                        }
                        <Td column="uptime"><small>{entity.uptime}</small></Td>
                      </Tr>
                    );
                  })
                }
              </Table>
              {
                !fromDashboard && filteredEntities.length !== 0
                ? <CommonPagination  {...paginationObj} callBackFunction={this.callBackFunction.bind(this)}/>
                : ''
              }
            </div>
        </div>
      </div>
    );
  }
}

// contrib/views/storm-vue/src/main/resources/ui/src/containers/TopologyListing.vue
<template>
  <div>
    <app-Breadcrumbs v-if="!fromDashboard" :items="linkList"></app-Breadcrumbs>
    <div class="box">
      <div class="box-header">
        <h4>Topology Listing</h4>
        <div v-if="fromDashboard" class="box-control">
          <router-link to="/topology" class="primary"><i class="fa fa-external-link"></i></router-link>
        </div>
      </div>
      <div :class="[{paddless: fromDashboard}, 'box-body']">
        <div v-if="!fromDashboard" class="input-group col-sm-4">
          <b-form-input v-model="filter" type="text" placeholder="Search By Topology Name"></b-form-input>
          <span class="input-group-btn">
            <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
          </span>
        </div>
        <CommonTable
          classname='no-margin'
          :items="items"
          :fields="fields"
          :showPagination="showPagination"
          :tableHeaderData="tableHeaderData"
        >
          <!-- Custom formatted value cells -->
          <template scope="{item}" slot="__name__">
            <router-link :to="{name: 'TopologyDetail', params: {topologyId: item.item.id}}">{{item.value}}</router-link>
          </template>
          <template scope="{item}" slot="__status__">
            <span :class="item.value | statusClass">{{item.value}}</span>
          </template>
          <template scope="{item}" slot="__uptime__">
            <small>{{item.value}}</small>
          </template>
        </CommonTable>
      </div>
    </div>
  </div>
</template>

<script>
  import TopologyREST from '@/rest/TopologyREST';
  import FilterUtils from '@/utils/FilterUtils';
  import CommonTable from '@/components/CommonTable';
  import Breadcrumbs from '@/components/Breadcrumbs';

  export default {
    name: 'TopologyListing',
    components: {
      'CommonTable': CommonTable,
      'app-Breadcrumbs' : Breadcrumbs
    },
    props: ["fromDashboard"],
    created(){
      this.fetchData();
    },
    data() {
      let tableFields = this.getTableFields();
      return {
        tableHeaderData:[
          {fieldName: "name", tooltip: "The name given to the topology by when it was submitted. Click the name to view the Topology's information.", isCustom: true},
          {fieldName: "status", tooltip: "The status can be one of ACTIVE, INACTIVE, KILLED, or REBALANCING.", isCustom: true},
          {fieldName: "assignedTotalMem", tooltip: "Assigned Total Memory by Scheduler."},
          {fieldName: "workersTotal", tooltip: "The number of Workers (processes)."},
          {fieldName: "executorsTotal", tooltip: "Executors are threads in a Worker process."},
          {fieldName: "tasksTotal", tooltip: "A Task is an instance of a Bolt or Spout. The number of Tasks is almost always equal to the number of Executors."},
          {fieldName: "owner", tooltip: "The user that submitted the Topology, if authentication is enabled."},
          {fieldName: "uptime", tooltip: "The time since the Topology was submitted.", isCustom: true}
        ],
        fields: tableFields,
        topologiesEntities: [],
        items: [],
        filter: null,
        showPagination: !this.fromDashboard ? true : false,
        linkList : this.getLinks()
      };
    },
    methods: {
      //Get all the table fields
      getTableFields(){
        let fields = {
          name: {label: 'Topology Name'},
          status: {label: 'Status'}
        };
        if(!this.fromDashboard) {
          let additionalFields = {
            assignedTotalMem: {label: 'Memory Assigned (MB)'},
            workersTotal: {label: 'Workers'},
            executorsTotal: {label: 'Executors'},
            tasksTotal: {label: 'Tasks'},
            owner: {label: 'Owner'}
          };
          Object.assign(fields, additionalFields);
        }
        Object.assign(fields, {uptime: {label: 'Uptime'}});
        return fields;
      },

      //Request call to get topology data
      fetchData(){
        TopologyREST.getSummary('topology').then((result) => {
          if(result.responseMessage !== undefined){
            console.error("Error in Topology Listing");
          } else {
            this.topologiesEntities = result.topologies;
            this.items = result.topologies;
          }
        });
      },

      //Filter by topology name
      onFilter(filterStr){
        if(typeof filterStr === 'string'){
          this.items = this.$options.filters.filterByKey(this.topologiesEntities, filterStr, 'name');
        } else {
          return this.items;
        }
      },

      getLinks(){
        var links = [
          {link: '#/', title: 'Dashboard'},
          {link: '#/topology', title: 'Topology Listing'}
        ];
        return links;
      }
    },
    filters: {
      filterByKey: FilterUtils.filterByKey,
      statusClass: FilterUtils.statusClass
    },
    watch:{
      //when filter value changes, it will call this method; being reactive
      filter(filterStr){
        this.onFilter(filterStr);
      },
      //if no data present in search result, hide pagination
      items(data){
        this.showPagination = !this.fromDashboard && data.length > 0;
      }
    }
  };
</script>
