// storm-app/src/containers/Dashboard.vue
<template>
  <div>
    <div class="row">
      <div class="col-sm-5">
        <app-clusterSummary></app-clusterSummary>
      </div>
      <div class="col-sm-7">
        <app-topologListing></app-topologListing>
        <app-supervisorSummary></app-supervisorSummary>
      </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
          <app-nimbusConfigSummary></app-nimbusConfigSummary>
        </div>
    </div>
  </div>
</template>
<script>
  import ClusterSummary from './ClusterSummary';
  import TopologyListing from './TopologyListing';
  import SupervisorSummary from './SupervisorSummary';
  import NimbusConfigSummary from './NimbusConfigSummary';

  export default {
    name: 'Dashboard',
    components: {
      'app-clusterSummary': ClusterSummary,
      'app-topologListing': TopologyListing,
      'app-supervisorSummary': SupervisorSummary,
      'app-nimbusConfigSummary': NimbusConfigSummary
    }
  };
</script>

// contrib/views/storm-ui/src/main/resources/ui/app/scripts/containers/Dashboard.jsx
import React, {Component} from 'react';
import BaseContainer from './BaseContainer';
import ClusterSummary from './ClusterSummary';
import TopologyListing from './TopologyListing';
import NimbusConfigSummary from './NimbusConfigSummary';
import SupervisorSummary from './SupervisorSummary';

export default class Dashboard extends Component {

  constructor(props) {
    super(props);
  }

  render() {
    return (
      <BaseContainer>
        <div className="row" style={{marginTop: '20px'}}>
          <div className="col-sm-5">
            <ClusterSummary />
          </div>
          <div className="col-sm-7">
            <TopologyListing fromDashboard={true} />
            <SupervisorSummary />
          </div>
        </div>
        <div className="row">
            <div className="col-sm-12">
              <NimbusConfigSummary />
            </div>
        </div>
      </BaseContainer>
    );
  }
}
