// contrib/views/storm-vue/src/main/resources/ui/src/containers/NimbusSummary.vue
<template>
  <div>
    <app-Breadcrumbs v-if="!fromDashboard" :items="linkList"></app-Breadcrumbs>
    <div class="box">
      <div class="box-header">
        <h4>Nimbus Summary</h4>
        <div v-if="fromDashboard" class="box-control">
          <router-link to="/nimbus" class="primary"><i class="fa fa-external-link"></i></router-link>
        </div>
      </div>
      <div :class="[{paddless: fromDashboard}, 'box-body']">
        <div v-if="!fromDashboard" class="input-group col-sm-4">
          <b-form-input v-model="filter" type="text" placeholder="Search By Host"></b-form-input>
          <span class="input-group-btn">
            <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
          </span>
        </div>
        <CommonTable classname='no-margin' :items="items" :fields="fields" :showPagination="showPagination" :tableHeaderData="tableHeaderData">
          <!-- Custom formatted value cells -->
          <template scope="{item}" slot="__hostName__">
            <a :href="item.item.nimbusLogLink" target="_blank">{{item.item.host+':'+item.item.port}}</a>
          </template>
          <template scope="{item}" slot="__status__">
            <span :class="item.value | statusClass">{{item.value}}</span>
          </template>
          <template scope="{item}" slot="__uptime__">
            <small>{{item.item.nimbusUpTime}}</small>
          </template>
        </CommonTable>
      </div>
    </div>
  </div>
</template>

<script>
  import TopologyREST from '@/rest/TopologyREST';
  import FilterUtils from '@/utils/FilterUtils';
  import CommonTable from '@/components/CommonTable';
  import Breadcrumbs from '@/components/Breadcrumbs';

  export default {
    name: 'NimbusSummary',
    components: {
      'CommonTable': CommonTable,
      'app-Breadcrumbs' : Breadcrumbs
    },
    props: ["fromDashboard"],
    created() {
      this.fetchData();
    },

    data() {
      let tableFields = this.getTableFields();
      return {
        tableHeaderData: [
          {fieldName: "hostName",tooltip: "Nimbus hostname and port number",isCustom: true},
          {fieldName: "status",tooltip: "Leader if this host is leader, Not a Leader for all other live hosts, note that these hosts may or may not be in leader lock queue, and Dead for hosts that are part of nimbus.seeds list but are not alive.",isCustom: true},
          {fieldName: "uptime",tooltip: "Time since this nimbus host has been running.",isCustom: true}
        ],
        fields: tableFields,
        entities: [],
        items: [],
        filter: null,
        showPagination: !this.fromDashboard ? true : false,
        linkList : this.getLinks()
      };
    },

    methods: {
      //Get all the table fields
      getTableFields() {
        let fields = {
          hostName: {label: 'Host:Port'},
          status: {label: 'Status'},
          uptime: {label: 'Uptime'}
        };
        return fields;
      },

      //Request call to get nimbus data
      fetchData() {
        TopologyREST.getSummary('nimbus').then((result) => {
          if (result.responseMessage !== undefined) {
            console.error("Error in NimbusSummary");
          } else {
            this.entities = result.nimbuses;
            this.items = result.nimbuses;
          }
        });
      },

      onFilter(filterStr) {
        if (typeof filterStr === 'string') {
          this.items = this.$options.filters.filterByKey(this.entities, filterStr, 'host');
        } else {
          return this.items;
        }
      },

      getLinks(){
        var links = [
          {link: '#/', title: 'Dashboard'},
          {link: '#/nimbus', title: 'Nimbus Summary'}
        ];
        return links;
      }

    },
    filters: {
      filterByKey: FilterUtils.filterByKey,
      statusClass: FilterUtils.statusClass
    },
    watch: {
      filter(filterStr) {
        this.onFilter(filterStr);
      }
    }
  };
</script>

// contrib/views/storm-ui/src/main/resources/ui/app/scripts/containers/NimbusSummary.jsx
import React, {Component} from 'react';
import _ from 'lodash';
import {
  Table,
  Thead,
  Th,
  Tr,
  Td,
  unsafe
} from 'reactable';
import FSReactToastr from '../components/FSReactToastr';
import {toastOpt, pageSize} from '../utils/Constants';
import TopologyREST from '../rest/TopologyREST';
import CommonNotification from '../components/CommonNotification';
import {OverlayTrigger, Tooltip} from 'react-bootstrap';
import Breadcrumbs from '../components/Breadcrumbs';
import CommonPagination from '../components/CommonPagination';
import Utils from '../utils/Utils';

export default class NimbusSummary extends Component{
  constructor(props){
    super(props);
    this.fetchData();
    this.state = {
      entities : [],
      filterValue: '',
      activePage: 1
    };
  }

  fetchData = () => {
    TopologyREST.getSummary('nimbus').then((results) => {
      if(results.responseMessage !== undefined){
        FSReactToastr.error(
          <CommonNotification flag="error" content={results.responseMessage}/>, '', toastOpt);
      } else {
        this.setState({entities : results.nimbuses});
      }
    });
  }

  getLinks(){
    var links = [
      {link: '#/', title: 'Dashboard'},
      {link: '#/nimbus', title: 'Nimbus Summary'}
    ];
    return links;
  }

  activeClass = (status) => {
    let classname="label ";
    switch(status){
    case 'Leader':
      classname += "label-success";
      break;// case 'Follower':
    //   classname += "label-warning";
    //   break;default:
      classname += "label-warning";
      break;
    }
    return classname;
  }

  handleFilter = (e) => {
    this.setState({filterValue: e.target.value.trim()});
  }

  callBackFunction = (eventKey) => {
    this.setState({activePage : eventKey});
  }

  render(){
    const {entities, filterValue, activePage} = this.state;
    const {fromDashboard} = this.props;
    const filteredEntities = Utils.filterByKey(entities, filterValue, 'host');
    const paginationObj = {
      activePage,
      pageSize,
      filteredEntities
    };
    return(
      <div className={fromDashboard ? "" : "container-fluid"}>
        {!fromDashboard ? <Breadcrumbs links={this.getLinks()} /> : ''}
        <div className="box">
            <div className="box-header">
                <h4>Nimbus Summary</h4>
                {fromDashboard ?
                <div className="box-control">
                  <a className="primary" href="#/nimbus"><i className="fa fa-external-link"></i></a>
                </div>
                : ''}
            </div>
            <div className={fromDashboard ? "box-body paddless" : "box-body"}>
              {!fromDashboard ?
              <div className="input-group col-sm-4">
                <input type="text" onKeyUp={this.handleFilter} className="form-control" placeholder="Search By Host" />
                <span className="input-group-btn">
                <button className="btn btn-primary" type="button"><i className="fa fa-search"></i></button>
                </span>
              </div>
              : ''}
              <Table className="table topology-table" noDataText="No records found." currentPage={0} >
                <Thead>
                  <Th column="host:Port"><OverlayTrigger placement="bottom" overlay={<Tooltip id="tooltip1">Nimbus hostname and port number</Tooltip>}><span>Host:Port</span></OverlayTrigger></Th>
                  <Th column="status"><OverlayTrigger placement="bottom" overlay={<Tooltip id="tooltip1">Leader if this host is leader, Not a Leader for all other live hosts, note that these hosts may or may not be in leader lock queue, and Dead for hosts that are part of nimbus.seeds list but are not alive.</Tooltip>}><span>Status</span></OverlayTrigger></Th>
                  <Th column="uptime"><OverlayTrigger placement="bottom" overlay={<Tooltip id="tooltip1">Time since this nimbus host has been running.</Tooltip>}><span>Uptime</span></OverlayTrigger></Th>
                </Thead>
                {
                  _.map(filteredEntities, (entity, i) => {
                    return (
                      <Tr key={i}>
                        <Td column="host:Port"><a href={entity.nimbusLogLink} target="_blank">{entity.host+':'+entity.port}</a></Td>
                        <Td column="status"><span className={this.activeClass(entity.status)}>{entity.status}</span></Td>
                        <Td column="uptime"><small>{entity.nimbusUpTime}</small></Td>
                      </Tr>
                    );
                  })
                }
              </Table>
              {
                !fromDashboard && filteredEntities.length !== 0
                ? <CommonPagination  {...paginationObj} callBackFunction={this.callBackFunction.bind(this)}/>
                : ''
              }
            </div>
        </div>
      </div>
    );
  }
}
