// contrib/views/storm-vue/src/main/resources/ui/src/containers/SupervisorSummary.vue
<template>
  <div>
    <app-Breadcrumbs v-if="!fromDashboard" :items="linkList"></app-Breadcrumbs>
    <div class="box">
      <div class="box-header">
        <h4>Supervisor Summary</h4>
        <div v-if="fromDashboard" class="box-control">
          <router-link to="/supervisor" class="primary"><i class="fa fa-external-link"></i></router-link>
        </div>
      </div>
      <div :class="[{paddless: fromDashboard}, 'box-body']">
        <div v-if="!fromDashboard" class="input-group col-sm-4">
          <b-form-input v-model="filter" type="text" placeholder="Search By Host"></b-form-input>
          <span class="input-group-btn">
            <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
          </span>
        </div>
        <CommonTable
          classname='no-margin supervisor-table'
          :items="items"
          :fields="fields"
          :showPagination="showPagination"
          :tableHeaderData="tableHeaderData"
        >
          <!-- Custom formatted value cells -->
          <template slot="__hostName__" scope="{item}">
            <a :href="item.item.logLink" target="_blank">{{item.item.host}}</a>
          </template>
          <template slot="__slots__" scope="{item}">
            <app-supervisorsummary-radial
              :graphData="[item.item.slotsUsed,item.item.slotsTotal]"
              :labels="labels" :width="width" :height="height"
              :innerRadius="innerRadius"
              :outerRadius="outerRadius" :color="color"></app-supervisorsummary-radial>
          </template>
          <template slot="__cpu__" scope="{item}">
            <app-supervisorsummary-radial
              :graphData="[item.item.usedCpu,item.item.totalCpu]"
              :labels="labels" :width="width" :height="height"
              :innerRadius="innerRadius"
              :outerRadius="outerRadius" :color="color"></app-supervisorsummary-radial>
          </template>
          <template slot="__memory__" scope="{item}">
            <app-supervisorsummary-radial
              :graphData="[item.item.usedMem,item.item.totalMem]"
              :labels="labels" :width="width" :height="height"
              :innerRadius="innerRadius"
              :outerRadius="outerRadius" :color="color"></app-supervisorsummary-radial>
          </template>
          <template scope="{item}" slot="__uptime__">
            <small>{{item.value}}</small>
          </template>
        </CommonTable>
      </div>
    </div>
  </div>
</template>

<script>
  import TopologyREST from '@/rest/TopologyREST';
  import FilterUtils from '@/utils/FilterUtils';
  import RadialChart from '@/components/RadialChart';
  import CommonTable from '@/components/CommonTable';
  import Breadcrumbs from '@/components/Breadcrumbs';
  import FSToaster from '@/utils/FSToaster';

  export default {
    name: 'SupervisorSummary',
    props: ["fromDashboard"],
    created(){
      this.fetchData();
    },

    data() {
      let tableFields = this.getTableFields();
      return {
        tableHeaderData:[
          {fieldName: "hostName", tooltip: "The hostname reported by the remote host. (Note that this hostname is not the result of a reverse lookup at the Nimbus node.)", isCustom: true},
          {fieldName: "slots", tooltip: "Slots are Workers (processes).", isCustom: true},
          {fieldName: "cpu", tooltip: "CPU that has been allocated.", isCustom: true},
          {fieldName: "memory", tooltip: "Memory that has been allocated.", isCustom: true},
          {fieldName: "uptime", tooltip: "The length of time a Supervisor has been registered to the cluster.", isCustom: true}
        ],
        fields: tableFields,
        entities: [],
        items: [],
        filter: null,
        labels : ['Used','Total'],
        width : null,
        height : null,
        innerRadius :19,
        outerRadius : 21,
        color: ["#bcbcbc", "#235693"],
        showPagination: !this.fromDashboard ? true : false,
        linkList : this.getLinks()
      };
    },

    methods: {
      //Get all the table fields
      getTableFields(){
        let fields = {
          hostName: {label: 'Host'},
          slots: {label: 'Slots'},
          cpu: {label: 'CPU'},
          memory: {label: 'Memory'},
          uptime: {label: 'Uptime'}
        };
        return fields;
      },

      //Request call to get nimbus data
      fetchData(){
        TopologyREST.getSummary('supervisor').then((result) => {
          if(result.responseMessage !== undefined){
            FSToaster.error("Error in SupervisorSummary");
          } else {
            this.entities = result.supervisors;
            this.items = result.supervisors;
          }
        });
      },

      onFilter(filterStr){
        if(typeof filterStr === 'string'){
          this.items = this.$options.filters.filterByKey(this.entities, filterStr, 'host');
        } else {
          return this.items;
        }
      },

      getLinks(){
        var links = [
          {link: '#/', title: 'Dashboard'},
          {link: '#/supervisor', title: 'Supervisor Summary'}
        ];
        return links;
      }

    },
    components : {
      'app-supervisorsummary-radial' : RadialChart,
      'CommonTable': CommonTable,
      'app-Breadcrumbs' : Breadcrumbs
    },
    filters: {
      filterByKey: FilterUtils.filterByKey,
      statusClass: FilterUtils.statusClass
    },
    watch:{
      filter(filterStr){
        this.onFilter(filterStr);
      }
    }
  };
</script>

// contrib/views/storm-ui/src/main/resources/ui/app/scripts/containers/SupervisorSummary.jsx
import React, {Component} from 'react';
import _ from 'lodash';
import {
  Table,
  Thead,
  Th,
  Tr,
  Td,
  unsafe
} from 'reactable';
import RadialChart  from '../components/RadialChart';
import FSReactToastr from '../components/FSReactToastr';
import {toastOpt, pageSize} from '../utils/Constants';
import TopologyREST from '../rest/TopologyREST';
import CommonNotification from '../components/CommonNotification';
import Breadcrumbs from '../components/Breadcrumbs';
import {OverlayTrigger, Tooltip} from 'react-bootstrap';
import CommonPagination from '../components/CommonPagination';
import Utils from '../utils/Utils';

export default class SupervisorSummary extends Component{
  constructor(props){
    super(props);
    this.fetchData();
    this.state = {
      entities : [],
      filterValue: '',
      activePage: 1
    };
  }

  fetchData = () => {
    TopologyREST.getSummary('supervisor').then((results) => {
      if(results.responseMessage !== undefined){
        FSReactToastr.error(
          <CommonNotification flag="error" content={results.responseMessage}/>, '', toastOpt);
      } else {
        this.setState({entities : results.supervisors});
      }
    });
  }

  getLinks(){
    var links = [
      {link: '#/', title: 'Dashboard'},
      {link: '#/supervisor', title: 'Supervisor Summary'}
    ];
    return links;
  }

  handleFilter = (e) => {
    this.setState({filterValue: e.target.value.trim()});
  }

  callBackFunction = (eventKey) => {
    this.setState({activePage : eventKey});
  }

  render(){
    const {entities, filterValue, activePage} = this.state;
    const {fromDashboard} = this.props;
    const filteredEntities = Utils.filterByKey(entities, filterValue, 'host');
    const paginationObj = {
      activePage,
      pageSize,
      filteredEntities
    };
    return(
      <div className={fromDashboard ? "" : "container-fluid"}>
        {!fromDashboard ? <Breadcrumbs links={this.getLinks()} /> : ''}
        <div className="box">
            <div className="box-header">
                <h4>Supervisor Summary</h4>
                {fromDashboard ?
                <div className="box-control">
                    <a className="primary" href="#/supervisor"><i className="fa fa-external-link"></i></a>
                </div>
                : ''}
            </div>
            <div className={fromDashboard ? "box-body paddless" : "box-body"}>
              {!fromDashboard ?
              <div className="input-group col-sm-4">
                <input type="text" onKeyUp={this.handleFilter} className="form-control" placeholder="Search By Host" />
                <span className="input-group-btn">
                <button className="btn btn-primary" type="button"><i className="fa fa-search"></i></button>
                </span>
              </div>
              : ''}
              <Table className="table no-margin supervisor-table" noDataText="No records found." currentPage={0} >
                <Thead>
                  <Th column="host"><OverlayTrigger placement="bottom" overlay={<Tooltip id="tooltip1">The hostname reported by the remote host. (Note that this hostname is not the result of a reverse lookup at the Nimbus node.)</Tooltip>}><span>Host</span></OverlayTrigger></Th>
                  <Th column="slots"><OverlayTrigger placement="bottom" overlay={<Tooltip id="tooltip1">Slots are Workers (processes).</Tooltip>}><span>Slots</span></OverlayTrigger></Th>
                  <Th column="cpu"><OverlayTrigger placement="bottom" overlay={<Tooltip id="tooltip1">CPU that has been allocated.</Tooltip>}><span>CPU</span></OverlayTrigger></Th>
                  <Th column="memory"><OverlayTrigger placement="bottom" overlay={<Tooltip id="tooltip1">Memory that has been allocated.</Tooltip>}><span>Memory</span></OverlayTrigger></Th>
                  <Th column="uptime"><OverlayTrigger placement="bottom" overlay={<Tooltip id="tooltip1">The length of time a Supervisor has been registered to the cluster.</Tooltip>}><span>Uptime</span></OverlayTrigger></Th>
                </Thead>
                {
                  _.map(filteredEntities, (entity, i) => {
                    return (
                      <Tr key={i}>
                        <Td column="host"><a href={entity.logLink} target="_blank">{entity.host}</a></Td>
                        <Td column="slots">
                          <RadialChart
                            data={[entity.slotsUsed,entity.slotsTotal]}
                            labels={['Used','Total']}
                            innerRadius={19}
                            outerRadius={21}
                            color={["#bcbcbc", "#235693"]}
                          />
                        </Td>
                        <Td column="cpu">
                          <RadialChart
                            data={[entity.usedCpu,entity.totalCpu]}
                            labels={['Used','Total']}
                            innerRadius={19}
                            outerRadius={21}
                            color={["#bcbcbc", "#235693"]}
                          />
                        </Td>
                        <Td column="memory">
                          <RadialChart
                            data={[entity.usedMem,entity.totalMem]}
                            labels={['Used','Total']}
                            innerRadius={19}
                            outerRadius={21}
                            color={["#bcbcbc", "#235693"]}
                          />
                        </Td>
                        <Td column="uptime"><small>{entity.uptime}</small></Td>
                      </Tr>
                    );
                  })
                }
              </Table>
              {
                !fromDashboard && filteredEntities.length !== 0
                ? <CommonPagination  {...paginationObj} callBackFunction={this.callBackFunction.bind(this)}/>
                : ''
              }
            </div>
        </div>
      </div>
    );
  }
}
