// storm-app/src/containers/TopologyDetailView.vue
<template>
  <div>
    <app-Breadcrumbs :items="items"></app-Breadcrumbs>
    <app-SearchLogs :id="topologyId"></app-SearchLogs>
    <div class="row">
      <div class="col-sm-12">
        <div class="box filter">
          <div class="box-body form-horizontal">
            <app-CommonWindowPanel
              KYC="detailView"
              :systemFlag="systemFlag"
              :debugFlag="debugFlag"
              :selectedWindowKey="selectedWindowKey"
              :windowOptions="windowOptions"
              :topologyStatus="topologyStatus"
              @handleTopologyAction="handleTopologyAction"
              @handleLogLevel="handleLogLevel"
            ></app-CommonWindowPanel>
            <app-LogLevelComponent v-if="showLogLevel" :topologyId="details.id"></app-LogLevelComponent>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-5">
        <div class="summary-tile">
          <div class="summary-title">Topology Summary</div>
          <div class="summary-body form-horizontal">
            <div class="form-group">
              <label class="col-sm-4 control-label">ID:</label>
              <div class="col-sm-8">
                <p class="form-control-static">{{details.id}}</p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-4 control-label">Owner:</label>
              <div class="col-sm-8">
                <p class="form-control-static">{{details.owner}}</p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-4 control-label">Status:</label>
              <div class="col-sm-8">
                <p class="form-control-static">{{details.status}}</p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-4 control-label">Uptime:</label>
              <div class="col-sm-8">
                <p class="form-control-static">{{details.uptime}}</p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-4 control-label">Workers:</label>
              <div class="col-sm-8">
                <p class="form-control-static">{{details.workersTotal}}</p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-4 control-label">Executors:</label>
              <div class="col-sm-8">
                <p class="form-control-static">{{details.executorsTotal}}</p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-4 control-label">Tasks:</label>
              <div class="col-sm-8">
                <p class="form-control-static">{{details.tasksTotal}}</p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-4 control-label">Memory:</label>
              <div class="col-sm-8">
                <p class="form-control-static">{{details.assignedTotalMem}}</p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-4 control-label">Worker-Host:Port:</label>
              <div class="col-sm-8">
                <p class="form-control-static preformatted">{{getWorkerData()}}</p>
              </div>
            </div>

          </div>
        </div>
      </div>
      <div class="col-sm-7">
        <div class="stats-tile">
          <div class="stats-title">Topology Stats</div>
          <div class="stats-body">
            <app-CommonTable
              classname='no-margin'
              :items="topStateItem"
              :fields="topStateFields"
              :showPagination="false"
              popoverPosition="top"
              :tableHeaderData="topStateHeaderData"
              >
            </app-CommonTable>
          </div>
        </div>
      </div>
    </div>

    <app-ToggleComponent :caption="details.name" type="topologyGraph">
      <div class="box-body">
        <app-TopologyGraph :graphData="graphData"></app-TopologyGraph>
      </div>
    </app-ToggleComponent>

    <app-ToggleComponent caption="Kafka Spout Lag"
      :lag="true"
      type="kafkaLag"
      :toggle="toggleGraphAndTable">
      <div class="box-body">
        <app-CommonTable
          v-if="toggleGraphAndTable"
          classname='no-margin'
          :items="topologyLag"
          :fields="topologyLagFields"
          :showPagination="false"
          :tableHeaderData="topLagHeaderData"
        >
      </app-CommonTable>
        <div v-else id="lag-graph">
          <app-BarChart
            ref="barChart"
            :width="screenWidth"
            :height="400"
            xAttr="spoutId-partition"
            yAttr="count"
            :data="barChartData"
            >
          </app-BarChart>
        </div>
      </div>
    </app-ToggleComponent>

    <app-ToggleComponent caption="Spouts">
      <div class="box-body">
        <div class="input-group col-sm-4">
          <input @input="filterChanged('spoutItems','constSpoutItems','spoutId', $event)" class="form-control" type="text" placeholder="Search By Topology Name" />
          <span class="input-group-btn">
            <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
          </span>
        </div>
        <app-CommonTable
          classname='no-margin'
          :items="spoutItems"
          :fields="spoutFields"
          :showPagination="true"
          :tableHeaderData="spoutHeaderData"
          :parentId = "topologyId"
          >

          <template scope="{item}" slot="__spoutId__">
            <router-link :to="{name: 'ComponentDetail', params: {topologyId: topologyId, componentName : item.value}}">{{item.value}}</router-link>
          </template>

        </app-CommonTable>
      </div>
    </app-ToggleComponent>

    <app-ToggleComponent caption="Bolts">
      <div class="box-body">
        <div class="input-group col-sm-4">
          <input @input="filterChanged('blotsItems','constBoltsItems','boltId', $event)" class="form-control" type="text" placeholder="Search By Topology Name" />
          <span class="input-group-btn">
            <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
          </span>
        </div>

        <app-CommonTable
          classname='no-margin'
          :items="blotsItems"
          :fields="boltsFields"
          :showPagination="true"
          :tableHeaderData="boltsHeaderData"
          :parentId = "topologyId"
          >

          <template scope="{item}" slot="__boltId__">
            <router-link :to="{name: 'ComponentDetail', params: {topologyId: topologyId, componentName : item.value}}">{{item.value}}</router-link>
          </template>

        </app-CommonTable>
      </div>
    </app-ToggleComponent>


    <app-ToggleComponent caption="Topology Configuration">
      <div class="box-body">
        <div class="input-group col-sm-4">
          <input @input="filterChanged('configItems','constConfigItems','Key', $event)" class="form-control" type="text" placeholder="Search By Topology Name" />
          <span class="input-group-btn">
            <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
          </span>
        </div>

        <app-CommonTable
          classname='no-margin'
          :items="configItems"
          :fields="configFields"
          :showPagination="true"
          :tableHeaderData="configHeaderData"
          >
        </app-CommonTable>
      </div>
    </app-ToggleComponent>




    <!-- debug modal  -->
    <app-FSModal
      modalTitle="Do you really want to debug this topology ? If yes, please, specify sampling percentage."
      cssClass="sm"
      ref="debugModelRef"
      @resovle="handleModelAction('debugModelRef','save')"
      @reject="handleModelAction('debugModelRef','cancel')"
      >
      <div slot="mbody">
        <input class="form-control" type="number" :min="0" :max="Number.MAX_SAFE_INTEGER" :value="debugSimplePCT" @input="inputTextChange('debugSimplePCT',$event)"/>
      </div>
    </app-FSModal>

    <!--  REBALANCING Modal -->
    <app-FSModal
      modalTitle="Rebalance Topology"
      cssClass="sm"
      ref="rebalanceModelRef"
      @resovle="handleModelAction('rebalanceModelRef','save')"
      @reject="handleModelAction('rebalanceModelRef','cancel')"
      >
      <div slot="mbody">
        <app-RebalanceTopology
          ref="rebalanceModal"
          :topologyId="details.id"
          :spoutArr="details.spouts"
          :boltArr="details.bolts"
          :topologyExecutors="details.workersTotal"
          >
        </app-rebalanceTopology>
     </div>
    </app-FSModal>

    <!-- Kill topology modal -->
    <app-FSModal
      modalTitle="Are you sure you want to kill this topology ? If yes, please, specify wait time in seconds."
      cssClass="sm"
      ref="killModelRef"
      @resovle="handleConfirmResolve('killModelRef')"
      @reject="handleConfirmReject('killModelRef')"
      >
      <div slot="mbody">
        <input class="form-control" type="number" :min="0" :max="Number.MAX_SAFE_INTEGER" :value="killWaitTime" @input="inputTextChange('killWaitTime',$event)"/>
     </div>
    </app-FSModal>

    <!-- debug confirmation box -->
    <app-FSModal
      ref="debugConfirmBox"
      @resovle="handleConfirmResolve('debugConfirmBox')"
      @reject="handleConfirmReject('debugConfirmBox')"
      :confirmBox="true"
      closeLabel="cancel"
      >
      <div slot="mbody">
       Do you really want to stop debugging this topology ?
     </div>
    </app-FSModal>

    <!-- topology active deactivate confirmation box -->
    <app-FSModal
      ref="activateConfirmBox"
      @resovle="handleConfirmResolve('activateConfirmBox')"
      @reject="handleConfirmReject('activateConfirmBox')"
      :confirmBox="true"
      closeLabel="cancel"
      >
      <div slot="mbody">
       {{activeTopologyBoxContent}}
     </div>
    </app-FSModal>

  </div>
</template>
<script>
  import Breadcrumbs from '@/components/Breadcrumbs';
  import FilterUtils from '@/utils/FilterUtils';
  import TopologyREST from '@/rest/TopologyREST';
  import _ from 'lodash';
  import SearchLogs from '@/components/SearchLogs';
  import CommonWindowPanel from '@/components/CommonWindowPanel';
  import FSModal from '@/components/FSModal';
  import RebalanceTopology from '@/components/RebalanceTopology';
  import LogLevelComponent from '@/components/LogLevelComponent';
  import CommonTable from '@/components/CommonTable';
  import ToggleComponent from '@/components/ToggleComponent';
  import BarChart from '@/components/BarChart';
  import TopologyGraph from '@/components/TopologyGraph';
  import {EventBus} from '@/utils/EventBus';

  export default{
    name : "TopologyDetailView",
    components : {
      "app-Breadcrumbs" : Breadcrumbs,
      "app-SearchLogs" : SearchLogs,
      "app-CommonWindowPanel" : CommonWindowPanel,
      "app-FSModal" : FSModal,
      "app-RebalanceTopology" : RebalanceTopology,
      "app-LogLevelComponent" : LogLevelComponent,
      "app-CommonTable" : CommonTable,
      "app-ToggleComponent" : ToggleComponent,
      "app-BarChart" : BarChart,
      "app-TopologyGraph": TopologyGraph
    },
    data(){
      return{
        topologyId : this.$route.params.topologyId,
        items : [],
        details: {},
        selectedWindowKey : {},
        windowOptions : [],
        systemFlag : false,
        debugFlag : false,
        killWaitTime : 30,
        topologyLag : [],
        debugSimplePCT:'',
        graphData:[],
        topologyStatus : '',
        activeTopologyBoxContent : '',
        topologyAction : '',
        showLogLevel : false,
        topStateItem : [],
        filter : null,
        topStateFields : this.getStateTableFields(),
        topStateHeaderData : this.getTopStateHeaderData(),
        topologyLagFields : this.getTopologyLagFields(),
        topLagHeaderData : this.getTopologyLagHeaderData(),
        toggleGraphAndTable : true,
        spoutItems : [],
        constSpoutItems :[],
        spoutFields : this.getSpoutFields(),
        spoutHeaderData : this.getSpoutHeaderData(),
        blotsItems : [],
        constBoltsItems:[],
        boltsFields : this.getBoltsFields(),
        boltsHeaderData : this.getBoltesHeaderData(),
        configItems : [],
        constConfigItems : [],
        configFields : this.getConfigFields(),
        configHeaderData : this.getConfigHeaderData(),
        screenWidth : window != window.parent ? 1100 : 1300,
        barChartData :[]
      };
    },
    created(){
      this.fetchDetails();
    },

    mounted () {
      EventBus.$on("switchCallBack", this.toggleSystem);
      EventBus.$on("handleWindowChange", this.handleWindowChange);
    },

    methods:{
      // populate link for breadcrumbs
      getLinks(){
        const links = [
          {link: '#/', title: 'Dashboard'},
          {link: '#/topology', title: 'Topology Listing'},
          {link: 'javascript:void(0);', title: this.details ? this.details.name : ""}
        ];
        return links;
      },

      // fetch initial data
      fetchDetails(){
        let self = this;
        const windowKeyVal = !_.isEmpty(self.selectedWindowKey) ? self.selectedWindowKey.value : ':all-time' ;
        let promiseArr=[
          TopologyREST.getTopologyDetails(self.topologyId,windowKeyVal,self.systemFlag),
          TopologyREST.getTopologyGraphData(self.topologyId,windowKeyVal),
          TopologyREST.getTopologyLag(self.topologyId)
        ];

        Promise.all(promiseArr).then((results) => {
          _.map(results, (result) => {
            if(result.responseMessage !== undefined){
              console.error("Error in TopologyDetailView");
            }
          });

          self.details = results[0];
          self.items = this.getLinks();
          self.windowOptions = FilterUtils.populateWindowsOptions(self.details.topologyStats);
          if(this.windowOptions.length === 0){
            this.selectedWindowKey = {};
          }
          self.debugSimplePCT = self.details.samplingPct;
          self.selectedWindowKey = {text : self.details.windowHint || 'All time', value : self.details.window || ':all-time'};
          self.graphData = results[1];
          self.topologyStatus = self.details !== undefined ? self.details.status : '';
          self.topologyLag = _.isEmpty(results[2]) ? [] : self.generateTopologyLagData(results[2]);
          self.topStateItem = self.details.topologyStats;
          self.spoutItems = self.details.spouts;
          self.constSpoutItems = self.details.spouts;
          self.blotsItems = self.details.bolts;
          self.constBoltsItems = self.details.bolts;
          self.configItems = this.dataTransformation(self.details.configuration);
          self.constConfigItems = this.dataTransformation(self.details.configuration);
          self.barChartData = this.populateLagGraphData(self.topologyLag);
        });
      },

      // data for topologyLag
      generateTopologyLagData(lagObj){
        const objKey = _.keys(lagObj);
        let arr = [];
        _.map(objKey, (o) => {
          let data = lagObj[o];
          const topicKeys = _.keys(data.spoutLagResult);
          _.map(topicKeys, (t) => {
            const topicName = t;
            const partitionData = data.spoutLagResult[t];
            const partitionKey = _.keys(partitionData);
            _.map(partitionKey, (pk) => {
              let obj = partitionData[pk];
              obj['spoutId'] = data.spoutId;
              obj['spoutType'] = data.spoutType;
              obj['partition'] = pk;
              obj['topic'] = topicName;
              arr.push(obj);
            });
          });
        });
        return arr;
      },

      // toggle for systemFlag and debugFlag
      toggleSystem(toggleStatus){
        this[toggleStatus] = !this[toggleStatus];
        if(toggleStatus === 'debugFlag'){
          !this.debugFlag ? this.debugEnableConfirmBox(this.debugFlag,'debugConfirmBox') : this.$refs.debugModelRef.show();
        } else if ( toggleStatus ==="kafkaLag"){
          this.toggleGraphAndTable = !this.toggleGraphAndTable;
        } else {
          this.fetchDetails();
        }
      },

      // windows select2 change
      handleWindowChange(obj){
        if(!_.isEmpty(obj)){
          this.selectedWindowKey = obj;
          this.fetchDetails();
        }
      },

      // Log levels
      handleLogLevel(){
        this.showLogLevel = !this.showLogLevel;
      },

      // All Modal action handler
      handleModelAction(modalType,action){
        if(action === 'save'){
          switch(modalType){
          case 'debugModelRef' : this.handleDebugSave(modalType,'enable');;
            break;
          case 'rebalanceModelRef' : this.handleRebalanceModalSave(modalType);
            break;
          case 'killModelRef' : this.handleTopologyKilled(modalType);
            break;
          default :
            break;
          }
        } else{
          switch(modalType){
          case 'debugModelRef' : this.debugFlag = !this.debugFlag;
            break;
          default :
            break;
          }
          this.$refs[modalType].hide();
        }
      },

      // debug inputTextChange handler
      inputTextChange(type,event){
        this[type] = +event.target.value;
      },

      debugEnableConfirmBox(confirm,modalType){
        if(!confirm){
          this.$refs[modalType].show();
        }
      },

      // confirmbox modal resovle
      handleConfirmResolve(modal){
        if(modal === "debugConfirmBox"){
          this.debugFlag = false;
        } else if(modal === "killModelRef"){
          this.handleTopologyKilled();
        } else if (modal === "activateConfirmBox"){
          this.handleTopologyActiveAndDeactive(this.topologyAction);
        }
        this.$refs[modal].hide();
      },

      // confirmBox modal reject
      handleConfirmReject(modal){
        if(modal === "debugConfirmBox"){
          this.debugFlag = !this.debugFlag;
        }
        this.$refs[modal].hide();
      },

      // handle debug change
      handleDebugSave(modal,toEnableFlag){
        const {debugSimplePCT,details} = this;
        this.$refs[modal].hide();
        TopologyREST.postDebugTopology(details.id,toEnableFlag,debugSimplePCT).then((result) => {
          if(result.responseMessage !== undefined){
            this.debugSimplePCT = details.samplingPct;
            console.error(result.responseMessage);
          } else {
            console.log("Debugging enabled successfully");
          }
        });
      },

      // Topology action handler
      handleTopologyAction(action){
        this.topologyAction = action;
        if(action === 'activate' || action === 'deactivate'){
          this.activeTopologyBoxContent = "Do you really want to "+action+" this topology ?";
          this.$refs.activateConfirmBox.show();
        } else if(action === 'rebalance'){
          this.$refs.rebalanceModelRef.show();
        } else if (action === "kill"){
          this.$refs.killModelRef.show();
        }
      },

      // topology active and deactive callback
      handleTopologyActiveAndDeactive(action){
        const {details} = this;
        TopologyREST.postActionOnTopology(details.id,action).then((result) => {
          if(result.responseMessage !== undefined){
            console.error(result.responseMessage);
          } else {
            this.topologyStatus = result.status;
            console.log("Topology "+action+"d successfully.");
          }
        });
      },

      // topology kill handler
      handleTopologyKilled(){
        const {killWaitTime,details} = this;
        TopologyREST.postActionOnTopology(details.id,'kill',killWaitTime).then((result) => {
          if(result.responseMessage !== undefined){
            console.error(result.responseMessage);
          } else {
            clearTimeout(this.clearTimeOutKill);
            this.clearTimeOutKill =  setTimeout(function () {
              console.log("Topology killed successfully.");
            },300);
          }
        });
      },

      handleRebalanceModalSave(modalType){
        if(this.$refs.rebalanceModal.validateData()){
          this.$refs[modalType].hide();
          this.$refs.rebalanceModal.handleSave().then((result) => {
            if(result.responseMessage !== undefined){
              console.error(result.responseMessage);
            } else {
              this.fetchDetails();
              clearTimeout(this.clearTimeOut);
              this.clearTimeOut =  setTimeout(function () {
                console.log("Topology rebalanced successfully.");
              },300);
            }
          });
        }
      },

      getWorkerData(){
        const {details} = this;
        let data='';
        _.map(details.workers,(worker,i) => {
          data += worker.host+':'+worker.port;
          if(i !== details.workers.length - 1){
            data += ', \n';
          }
        });
        return data;
      },

      getStateTableFields(){
        return {
          windowPretty: {label: 'Window'},
          emitted: {label: 'Emitted'},
          transferred: {label: 'Transferred'},
          completeLatency: {label: 'Complete Latency (ms)'},
          acked: {label: 'Acked'},
          failed: {label: 'Failed'}
        };
      },

      getTopStateHeaderData(){
        return [
          {fieldName : "windowPretty" , tooltip : "The past period of time for which the statistics apply."},
          {fieldName : "emitted" , tooltip : "The number of Tuples emitted." },
          {fieldName : "transferred" , tooltip : "The number of Tuples emitted that sent to one or more bolts." },
          {fieldName : "completeLatency" , tooltip : "The average time a Tuple tree takes to be completely processed by the Topology. A value of 0 is expected if no acking is done." },
          {fieldName : "acked" , tooltip : "The number of Tuple trees successfully processed. A value of 0 is expected if no acking is done." },
          {fieldName : "failed" , tooltip : "The number of Tuple trees that were explicitly failed or timed out before acking was completed. A value of 0 is expected if no acking is done." }
        ];
      },

      getTopologyLagHeaderData(){
        return [
          {fieldName : "spoutId" , tooltip : "Id"},
          {fieldName : "topic" , tooltip : "Topic"},
          {fieldName : "partition" , tooltip : "Partition"},
          {fieldName : "logHeadOffset" , tooltip : "Latest Offset"},
          {fieldName : "consumerCommittedOffset" , tooltip : "Spout Committed Offset"},
          {fieldName : "lag" , tooltip : "Lag"}
        ];
      },

      getTopologyLagFields(){
        return {
          spoutId: {label: 'Id'},
          topic: {label: 'Topic'},
          partition: {label: 'Partition'},
          logHeadOffset: {label: 'Latest Offset'},
          consumerCommittedOffset: {label: 'Spout Committed Offset'},
          lag: {label: 'Lag'}
        };
      },

      getSpoutHeaderData(){
        return [
          {fieldName : "spoutId" , tooltip : "The ID assigned to a the Component by the Topology. Click on the name to view the Component's page.", isCustom :true},
          {fieldName : "executors" , tooltip : "Executors are threads in a Worker process."},
          {fieldName : "tasks" , tooltip : "A Task is an instance of a Bolt or Spout. The number of Tasks is almost always equal to the number of Executors."},
          {fieldName : "emitted" , tooltip : "The number of Tuples emitted."},
          {fieldName : "transferred" , tooltip : "The number of Tuples emitted that sent to one or more bolts."},
          {fieldName : "completeLatency" , tooltip : "The average time a Tuple tree takes to be completely processed by the Topology. A value of 0 is expected if no acking is done."},
          {fieldName : "acked" , tooltip : "The number of Tuple trees successfully processed. A value of 0 is expected if no acking is done."},
          {fieldName : "failed" , tooltip : "The number of Tuple trees that were explicitly failed or timed out before acking was completed. A value of 0 is expected if no acking is done."},
          {fieldName : "errorHost" , tooltip : "Error Host:Port"},
          {fieldName : "lastError" , tooltip : "Last Error"},
          {fieldName : "errorTime" , tooltip : "Error Time"}
        ];
      },

      getSpoutFields(){
        return{
          spoutId : {label : "Id"},
          executors : {label : "Executors"},
          tasks : {label : "Tasks"},
          emitted : {label : "Emitted"},
          transferred : {label : "Transferred"},
          completeLatency : {label : "Complete Latency (ms)"},
          acked : {label : "Acked"},
          failed : {label : "Failed"},
          errorHost : {label : "Error Host:Port"},
          lastError : {label : "Last Error"},
          errorTime : {label : "Error Time"}
        };
      },

      getBoltsFields(){
        return {
          boltId : {label : "Id"},
          executors : {label : "Executors"},
          tasks : {label : "Tasks"},
          emitted : {label : "Emitted"},
          transferred : {label : "Transferred"},
          capacity : {label : "Capacity (last 10m)"},
          executeLatency : {label : "Execute Latency (ms)"},
          executed : {label : "Executed"},
          processLatency : {label : "Process Latency (ms)"},
          acked : {label : "Acked"},
          failed : {label : "Failed"},
          errorHost : {label : "Error Host:Port"},
          lastError : {label : "Last Error"},
          errorTime : {label : "Error Time"}
        };
      },

      getBoltesHeaderData(){
        return [
          {fieldName : "boltId" , tooltip : "The ID assigned to a the Component by the Topology. Click on the name to view the Component's page.", isCustom : true},
          {fieldName : "executors" , tooltip : "Executors are threads in a Worker process."},
          {fieldName : "tasks" , tooltip : "A Task is an instance of a Bolt or Spout. The number of Tasks is almost always equal to the number of Executors."},
          {fieldName : "emitted" , tooltip : "The number of Tuples emitted."},
          {fieldName : "transferred" , tooltip : "The number of Tuples emitted that sent to one or more bolts."},
          {fieldName : "capacity" , tooltip : "If this is around 1.0, the corresponding Bolt is running as fast as it can, so you may want to increase the Bolt's parallelism. This is (number executed * average execute latency) / measurement time."},
          {fieldName : "executeLatency" , tooltip : "The average time a Tuple spends in the execute method. The execute method may complete without sending an Ack for the tuple."},
          {fieldName : "executed" , tooltip : "The number of incoming Tuples processed."},
          {fieldName : "processLatency" , tooltip : "The average time it takes to Ack a Tuple after it is first received.  Bolts that join, aggregate or batch may not Ack a tuple until a number of other Tuples have been received."},
          {fieldName : "acked" , tooltip : "The number of Tuples acknowledged by this Bolt."},
          {fieldName : "failed" , tooltip : "The number of tuples Failed by this Bolt."},
          {fieldName : "errorHost" , tooltip : "Error Host:Port"},
          {fieldName : "lastError" , tooltip : "Last Error"},
          {fieldName : "errorTime" , tooltip : "Error Time"}
        ];
      },

      getConfigFields(){
        return{
          Key : {label : "Key"},
          value : {label : "Value"}
        };
      },

      getConfigHeaderData(){
        return[
          {fieldName : "Key"},
          {fieldName : "value"}
        ];
      },

      // toggleTableAndGraphFUNC(){
      //   this.toggleGraphAndTable = !this.toggleGraphAndTable;
      // },

      dataTransformation(obj){
        let arr = [];
        const list = _.keys(obj);
        _.map(list, (l) => {
          arr.push({Key : l, value : obj[l]});
        });
        return arr;
      },

      //Filter by topology name
      filterChanged(typeVal, fixTypeVal, key ,event){
        const filterStr = event.target.value.trim();
        this[typeVal] = FilterUtils.filterByKey(this[fixTypeVal], filterStr,key);
      },

      populateLagGraphData(){
        let graphArr=[];
        _.map(this.topologyLag, (t) => {
          graphArr.push({
            'Latest Offset': t.logHeadOffset,
            'Spout Committed Offset': t.consumerCommittedOffset,
            'spoutId-partition': t.spoutId+'-'+t.partition
          });
        });
        return graphArr;
      }
    }
  };
</script>

// contrib/views/storm-ui/src/main/resources/ui/app/scripts/containers/TopologyDetailView.jsx
import React, {Component} from 'react';
import ReactDOM from 'react-dom';
import BaseContainer from './BaseContainer';
import SearchLogs from '../components/SearchLogs';
import TopologyREST from '../rest/TopologyREST';
import {Accordion, Panel} from 'react-bootstrap';
import TopologyGraph from '../components/TopologyGraph';
import {
  Table,
  Thead,
  Th,
  Tr,
  Td,
  unsafe
} from 'reactable';
import CommonPagination from '../components/CommonPagination';
import {Link} from 'react-router';
import {toastOpt,pageSize} from '../utils/Constants';
import Utils from '../utils/Utils';
import FSReactToastr from '../components/FSReactToastr';
import CommonNotification from '../components/CommonNotification';
import Breadcrumbs from '../components/Breadcrumbs';
import Modal from '../components/FSModel';
import CommonWindowPanel from '../components/CommonWindowPanel';
import RebalanceTopology from '../components/RebalanceTopology';
import LogLevelComponent  from '../components/LogLevelComponent';
import CommonSwitchComponent from '../components/CommonSwitchComponent';
import BarChart from '../components/BarChart';
import CommonExpanded from '../components/CommonExpanded';

export default class TopologyDetailView extends Component {
  constructor(props){
    super(props);
    this.state = {
      details: {},
      spotActivePage : 1,
      boltsActivePage : 1,
      topologyActivePage : 1,
      spotFilterValue : '',
      blotFilterValue : '',
      topologyFilterValue : '',
      selectedWindowKey : {label : 'All time' , value : ':all-time'},
      windowOptions : [],
      systemFlag : false,
      killWaitTime : 30,
      showLogLevel : false,
      topologyLagFlag : false,
      topologyLagPage : 1,
      toggleGraphAndTable: true,
      expandGraph : true,
      expandSpout : true,
      expandBolt : true,
      expandConfig : false
    };
    this.fetchDetails();
  }
  fetchDetails(){
    const {selectedWindowKey,systemFlag} = this.state;
    let promiseArr=[
      TopologyREST.getTopologyDetails(this.props.params.id,selectedWindowKey.value,systemFlag),
      TopologyREST.getTopologyGraphData(this.props.params.id,selectedWindowKey.value),
      TopologyREST.getTopologyLag(this.props.params.id)
    ];

    Promise.all(promiseArr).then((results) => {
      _.map(results, (result) => {
        if(result.responseMessage !== undefined){
          FSReactToastr.error(
            <CommonNotification flag="error" content={result.responseMessage}/>, '', toastOpt);
        }
      });

      let stateObj = {};
      stateObj.details = results[0];
      stateObj.windowOptions = Utils.populateWindowsOptions(stateObj.details.topologyStats);
      stateObj.debugSimplePCT = stateObj.details.samplingPct;
      stateObj.selectedWindowKey = {label : stateObj.details.windowHint, value : stateObj.details.window};
      stateObj.graphData = results[1];
      stateObj.topologyLag = results[2];
      this.setState(stateObj);
    });
  }

  componentDidUpdate(){
    if(this.refs.barChart){
      ReactDOM.findDOMNode(document.getElementById('lag-graph')).appendChild(this.refs.barChart.legendsEl);
    }
  }

  handleWindowChange = (obj) => {
    if(!_.isEmpty(obj)){
      this.setState({selectedWindowKey : obj}, () => {
        this.fetchDetails();
      });
    }
  }

  getWorkerData = () => {
    const {details} = this.state;
    let data='';
    _.map(details.workers,(worker,i) => {
      data += worker.host+':'+worker.port;
      if(i !== details.workers.length - 1){
        data += ', \n';
      }
    });
    return data;
  }

  getDateFormat = (d) => {
    let obj = new Date(d * 1000);
    return <span>{obj.toLocaleDateString() + ' ' + obj.toLocaleTimeString()}</span>;
  }

  handleFilter = (section,e) => {
    switch(section){
    case 'spout' : this.setState({spotFilterValue :  e.target.value.trim()});
      break;
    case 'bolt' : this.setState({blotFilterValue :  e.target.value.trim()});
      break;
    case 'topologyConfig' : this.setState({topologyFilterValue :  e.target.value.trim()});
      break;
    default :
      break;
    };
  }

  callBackFunction = (eventKey,tableName) => {
    switch(tableName){
    case 'spout' : this.setState({spotActivePage : eventKey});
      break;
    case 'bolt' : this.setState({boltsActivePage : eventKey});
      break;
    case 'topologyConfig' : this.setState({topologyActivePage : eventKey});
      break;
    case 'topologyLag' : this.setState({topologyLagPage : eventKey});
      break;
    default :
      break;
    };
  }

  getLinks(){
    const {details} = this.state;
    var links = [
      {link: '#/', title: 'Dashboard'},
      {link: '#/topology', title: 'Topology Listing'},
      {link: 'javascript:void(0);', title: details.name? details.name : ""}
    ];
    return links;
  }

  toggleSystem = (toggleStatus) => {
    let stateObj = _.cloneDeep(this.state);
    stateObj[toggleStatus] = !stateObj[toggleStatus];
    this.setState(stateObj,() => {
      if(toggleStatus === 'debugFlag'){
        !stateObj.debugFlag ? this.debugEnableConfirmBox(stateObj.debugFlag,'debugModelRef') : this.refs.debugModelRef.show();
      } else {
        this.fetchDetails();
      }
    });
  }

  handleModelAction = (modalType,action) => {
    if(action === 'save'){
      switch(modalType){
      case 'debugModelRef' : this.handleDebugSave(modalType,'enable');;
        break;
      case 'rebalanceModelRef' : this.handleRebalanceModalSave(modalType);
        break;
      case 'killModelRef' : this.handleTopologyKilled(modalType);
        break;
      default :
        break;
      }
    } else{
      switch(modalType){
      case 'debugModelRef' : Utils.hideFSModal.call(this,modalType,'callBack').then((res) => {
        this.setState({debugFlag : !this.state.debugFlag});
      });
        break;
      default : Utils.hideFSModal.call(this,modalType);
        break;
      }
    }
  }

  inputTextChange = (type,e) => {
    let stateObj = _.cloneDeep(this.state);
    stateObj[type] = e.target.value;
    this.setState(stateObj);
  }

  debugEnableConfirmBox = (confirm,modalType) => {
    if(!confirm){
      this.refs.BaseContainer.refs.Confirm.show({title: 'Do you really want to stop debugging this topology ?"'}).then((confirmBox) => {
        this.setState({debugSimplePCT : 0}, () => {
          this.handleDebugSave(modalType,'disable');
          confirmBox.cancel();
        });
      }, () => {
        this.setState({debugFlag : true});
      });
    }
  }

  handleDebugSave = (modal,toEnableFlag) => {
    const {debugSimplePCT,details} = this.state;
    Utils.hideFSModal.call(this,modal);
    TopologyREST.postDebugTopology(details.id,toEnableFlag,debugSimplePCT).then((result) => {
      if(result.responseMessage !== undefined){
        this.setState({debugSimplePCT : details.samplingPct});
        FSReactToastr.error(
          <CommonNotification flag="error" content={result.responseMessage}/>, '', toastOpt);
      } else {
        FSReactToastr.success(<strong>Debugging enabled successfully.</strong>);
      }
    });
  }

  handleRebalanceModalSave = (modalType) => {
    if(this.refs.rebalanceModal.validateData()){
      Utils.hideFSModal.call(this,modalType);
      this.refs.rebalanceModal.handleSave().then((result) => {
        if(result.responseMessage !== undefined){
          FSReactToastr.error(
            <CommonNotification flag="error" content={result.responseMessage}/>, '', toastOpt);
        } else {
          this.fetchDetails();
          clearTimeout(this.clearTimeOut);
          this.clearTimeOut =  setTimeout(function () {
            FSReactToastr.success(<strong>Topology rebalanced successfully.</strong>);
          },300);
        }
      });
    }
  }

  handleTopologyAction = (action) => {
    if(action === 'activate' || action === 'deactivate'){
      this.handleTopologyActiveAndDeactive(action);
    } else if(action === 'rebalance'){
      this.refs.rebalanceModelRef.show();
    } else if (action === "kill"){
      this.refs.killModelRef.show();
    }
  }

  handleTopologyKilled = (modalType) => {
    const {killWaitTime,details} = this.state;
    TopologyREST.postActionOnTopology(details.id,'kill',killWaitTime).then((result) => {
      if(result.responseMessage !== undefined){
        FSReactToastr.error(
          <CommonNotification flag="error" content={result.responseMessage}/>, '', toastOpt);
      } else {
        clearTimeout(this.clearTimeOutKill);
        this.clearTimeOutKill =  setTimeout(function () {
          FSReactToastr.success(<strong>"Topology killed successfully."</strong>);
        },300);
      }
    });
  }

  handleTopologyActiveAndDeactive = (action) => {
    this.refs.BaseContainer.refs.Confirm.show({title: "Do you really want to "+action+" this topology ?"}).then((confirmBox) => {
      const {details} = this.state;
      TopologyREST.postActionOnTopology(details.id,action).then((result) => {
        if(result.responseMessage !== undefined){
          FSReactToastr.error(
            <CommonNotification flag="error" content={result.responseMessage}/>, '', toastOpt);
        } else {
          FSReactToastr.success(<strong>"Topology "+action+" successfully."</strong>);
        }
      });
      confirmBox.cancel();
    }, () => {});
  }

  handleLogLevel = () => {
    this.setState({showLogLevel : !this.state.showLogLevel});
  }

  toggleKafkaLag = (action,event) => {
    event.stopPropagation();
    this.setState({toggleGraphAndTable : !this.state.toggleGraphAndTable});
  }

  lagAccodianClick = () => {
    this.setState({topologyLagFlag : !this.state.topologyLagFlag});
  }

  commonOnSelectFunction = (type) => {
    let tempState = _.cloneDeep(this.state);
    tempState[type] = !tempState[type];
    this.setState(tempState);
  }

  render() {
    const {details,spotActivePage,boltsActivePage,topologyActivePage,spotFilterValue,blotFilterValue,topologyFilterValue,
      graphData,selectedWindowKey,windowOptions,systemFlag,debugFlag,debugSimplePCT,killWaitTime,showLogLevel,
      topologyLagFlag,topologyLagPage,topologyLag,toggleGraphAndTable,expandGraph,expandSpout,expandBolt,expandConfig} = this.state;
    const spoutfilteredEntities = Utils.filterByKey(details.spouts || [], spotFilterValue,'spoutId');
    const blotfilteredEntities = Utils.filterByKey(details.bolts || [], blotFilterValue,'boltId');
    const topologyfilteredEntities = Utils.filterByKey(_.keys(details.configuration) || [], topologyFilterValue);
    const spotPaginationObj = {
      activePage :spotActivePage,
      pageSize,
      filteredEntities : spoutfilteredEntities
    };
    const boltPaginationObj = {
      activePage :boltsActivePage,
      pageSize,
      filteredEntities : blotfilteredEntities
    };
    const topologyPaginationObj = {
      activePage :topologyActivePage,
      pageSize,
      filteredEntities : topologyfilteredEntities
    };
    const graphDataObj = _.isEmpty(graphData) && graphData === undefined ? {} : graphData;
    const topologyStatus = details !== undefined ? details.status : '';
    const lagPanelHeader = <h4>
      Kafka Spout Lag
      <CommonExpanded  expandFlag={topologyLagFlag}/>
      {
        <CommonSwitchComponent KYC="kafka" checked={toggleGraphAndTable} textON="Table" textOFF="Graph" switchCallBack={this.toggleKafkaLag.bind(this,'kafkaSpoutLag')} />
      }
    </h4>;

    const graphPanelHead = <h4> {details.name}
                              <CommonExpanded  expandFlag={expandGraph}/></h4>;

    const spoutPanelHead = <h4> Spouts
                            <CommonExpanded  expandFlag={expandSpout}/></h4>;

    const boltPanelHead = <h4> Bolts
                            <CommonExpanded  expandFlag={expandBolt}/></h4>;

    const configPanelHead = <h4> Topology Configuration
                              <CommonExpanded  expandFlag={expandConfig}/></h4>;

    return (
    <BaseContainer ref="BaseContainer">
      <Breadcrumbs links={this.getLinks()} />
      <SearchLogs
        id={this.props.params.id}
      />
      <div className="row">
        <div className="col-sm-12">
          <div className="box filter">
            <div className="box-body form-horizontal">
              <CommonWindowPanel KYC="detailView" selectedWindowKey={selectedWindowKey} windowOptions={windowOptions} status={topologyStatus} systemFlag={systemFlag} debugFlag={debugFlag} handleWindowChange={this.handleWindowChange.bind(this)} toggleSystem={this.toggleSystem.bind(this)} handleTopologyAction={this.handleTopologyAction.bind(this)} handleLogLevel={this.handleLogLevel.bind(this)} topologyStatus={topologyStatus}/>
              {
                showLogLevel
                ? <LogLevelComponent topologyId={details.id}/>
                : ''
              }
            </div>
          </div>
        </div>
      </div>
      <div className="row">
        <div className="col-sm-5">
          <div className="summary-tile">
            <div className="summary-title">Topology Summary</div>
            <div className="summary-body form-horizontal">
              <div className="form-group">
                <label className="col-sm-4 control-label">ID:</label>
                <div className="col-sm-8">
                  <p className="form-control-static">{details.id}</p>
                </div>
              </div>
              <div className="form-group">
                <label className="col-sm-4 control-label">Owner:</label>
                <div className="col-sm-8">
                  <p className="form-control-static">{details.owner}</p>
                </div>
              </div>
              <div className="form-group">
                <label className="col-sm-4 control-label">Status:</label>
                <div className="col-sm-8">
                  <p className="form-control-static">{details.status}</p>
                </div>
              </div>
              <div className="form-group">
                <label className="col-sm-4 control-label">Uptime:</label>
                <div className="col-sm-8">
                  <p className="form-control-static">{details.uptime}</p>
                </div>
              </div>
              <div className="form-group">
                <label className="col-sm-4 control-label">Workers:</label>
                <div className="col-sm-8">
                  <p className="form-control-static">{details.workersTotal}</p>
                </div>
              </div>
              <div className="form-group">
                <label className="col-sm-4 control-label">Executors:</label>
                <div className="col-sm-8">
                  <p className="form-control-static">{details.executorsTotal}</p>
                </div>
              </div>
              <div className="form-group">
                <label className="col-sm-4 control-label">Tasks:</label>
                <div className="col-sm-8">
                  <p className="form-control-static">{details.tasksTotal}</p>
                </div>
              </div>
              <div className="form-group">
                <label className="col-sm-4 control-label">Memory:</label>
                <div className="col-sm-8">
                  <p className="form-control-static">{details.assignedTotalMem}</p>
                </div>
              </div>
              <div className="form-group">
                <label className="col-sm-4 control-label">Worker-Host:Port:</label>
                <div className="col-sm-8">
                  <p className="form-control-static preformatted">{this.getWorkerData()}</p>
                </div>
              </div>

            </div>
          </div>
        </div>
        <div className="col-sm-7">
          <div className="stats-tile">
            <div className="stats-title">Topology Stats</div>
            <div className="stats-body">
              <Table className="table table-enlarge" noDataText="No records found." currentPage={0} >
                <Thead>
                  <Th column="windowPretty"  title="The past period of time for which the statistics apply.">Window</Th>
                  <Th column="emitted"  title="The number of Tuples emitted.">Emitted</Th>
                  <Th column="transferred"  title="The number of Tuples emitted that sent to one or more bolts.">Transferred</Th>
                  <Th column="completeLatency"  title="The average time a Tuple tree takes to be completely processed by the Topology. A value of 0 is expected if no acking is done.">Complete Latency (ms)</Th>
                  <Th column="acked"  title="The number of Tuple trees successfully processed. A value of 0 is expected if no acking is done.">Acked</Th>
                  <Th column="failed"  title="The number of Tuple trees that were explicitly failed or timed out before acking was completed. A value of 0 is expected if no acking is done.">Failed</Th>
                </Thead>
                {
                  _.map(details.topologyStats,(s,i) => {
                    return(
                      <Tr key={i}>
                        <Td column="windowPretty">{s.windowPretty}</Td>
                        <Td column="emitted">{s.emitted}</Td>
                        <Td column="transferred">{s.transferred}</Td>
                        <Td column="completeLatency">{s.completeLatency}</Td>
                        <Td column="acked">{s.acked}</Td>
                        <Td column="failed">{s.failed}</Td>
                      </Tr>
                    );
                  })
                }
              </Table>
            </div>
          </div>
        </div>
      </div>
      <Panel expanded={expandGraph} collapsible header={graphPanelHead} eventKey="1" onSelect={this.commonOnSelectFunction.bind(this,'expandGraph')}>
        <div className="graph-bg">
          <TopologyGraph
            data={graphDataObj}
          />
        </div>
      </Panel>
      {
        !_.isEmpty(topologyLag)
        ? <Panel expanded={topologyLagFlag} collapsible header={lagPanelHeader} eventKey="3" onSelect={this.lagAccodianClick.bind(this)}>
          {
            toggleGraphAndTable
            ? <Table className="table no-margin"  noDataText="No found !"  currentPage={topologyLagPage-1} itemsPerPage={pageSize}>
                <Thead>
                  <Th column="spoutId" title="Id">Id</Th>
                  <Th column="topic" title="Topic">Topic</Th>
                  <Th column="partition" title="Partition">Partition</Th>
                  <Th column="logHeadOffset" title="Latest Offset"></Th>
                  <Th column="consumerCommittedOffset" title="Spout Committed Offset">Spout Committed Offset</Th>
                  <Th column="lag" title="Lag">Lag</Th>
                </Thead>
              </Table>
            : <div id="lag-graph">
                <BarChart
                  ref="barChart"
                  width={window != window.parent ? 1100 : 1300}
                  height={400}
                  xAttr="spoutId-partition"
                  yAttr="count"
                  data={[{'Latest Offset':23,'Spout Committed Offset': 100,'spoutId-partition': 'partition'},{'Latest Offset':300,'Spout Committed Offset': 380,'spoutId-partition': 'partition 23'}]}
                />
            </div>
          }


          </Panel>
        : null
      }
      <Panel expanded={expandSpout} collapsible header={spoutPanelHead} eventKey="3" onSelect={this.commonOnSelectFunction.bind(this,'expandSpout')}>
        <div className="input-group col-sm-4">
          <input type="text"  onKeyUp={this.handleFilter.bind(this,'spout')} className="form-control" placeholder="Search By Id" />
          <span className="input-group-btn">
          <button className="btn btn-primary" type="button"><i className="fa fa-search"></i></button>
          </span>
        </div>
        <div className="table-responsive">
        <Table className="table no-margin"  noDataText="No spouts found !"  currentPage={spotActivePage-1} itemsPerPage={pageSize}>
          <Thead>
            <Th column="spoutId" title="The ID assigned to a the Component by the Topology. Click on the name to view the Component's page.">Id</Th>
            <Th column="executors" title="Executors are threads in a Worker process.">Executors</Th>
            <Th column="tasks" title="A Task is an instance of a Bolt or Spout. The number of Tasks is almost always equal to the number of Executors.">Tasks</Th>
            <Th column="emitted" title="The number of Tuples emitted.">Emitted</Th>
            <Th column="transferred" title="The number of Tuples emitted that sent to one or more bolts.">Transferred</Th>
            <Th column="completeLatency" title="The average time a Tuple tree takes to be completely processed by the Topology. A value of 0 is expected if no acking is done.">Complete Latency (ms)</Th>
            <Th column="acked" title="The number of Tuple trees successfully processed. A value of 0 is expected if no acking is done.">Acked</Th>
            <Th column="failed" title="The number of Tuple trees that were explicitly failed or timed out before acking was completed. A value of 0 is expected if no acking is done.">Failed</Th>
            <Th column="errorHost" >Error Host:Port</Th>
            <Th column="lastError" >Last Error</Th>
            <Th column="errorTime" >Error Time</Th>
          </Thead>
          {
            _.map(spoutfilteredEntities, (s,i) => {
              return(
                <Tr key={i}>
                  <Td column="spoutId"><Link to={`/topology/${details.id}/component/${s.spoutId}`}>{s.spoutId}</Link></Td>
                  <Td column="executors">{s.executors}</Td>
                  <Td column="tasks">{s.tasks}</Td>
                  <Td column="emitted">{s.emitted}</Td>
                  <Td column="transferred">{s.transferred}</Td>
                  <Td column="completeLatency">{s.completeLatency}</Td>
                  <Td column="acked">{s.acked}</Td>
                  <Td column="failed">{s.failed}</Td>
                  <Td column="errorHost">{s.errorHost !== '' ? s.errorHost+s.errorPort : '' }</Td>
                  <Td column="lastError">{s.lastError}</Td>
                  <Td column="errorTime">{s.errorTime !== null && s.errorTime !== 0 ? this.getDateFormat(s.errorTime) : '' }</Td>
                </Tr>
              );
            })
          }
        </Table>
        </div>
        {
          spoutfilteredEntities.length !== 0
          ? <CommonPagination  {...spotPaginationObj} callBackFunction={this.callBackFunction.bind(this)} tableName="spout"/>
          : ''
        }
      </Panel>
      <Panel expanded={expandBolt} collapsible header={boltPanelHead} eventKey="4" onSelect={this.commonOnSelectFunction.bind(this,'expandBolt')}>
        <div className="input-group col-sm-4">
          <input type="text"  onKeyUp={this.handleFilter.bind(this,'bolt')} className="form-control" placeholder="Search By Id" />
          <span className="input-group-btn">
          <button className="btn btn-primary" type="button"><i className="fa fa-search"></i></button>
          </span>
        </div>
        <div className="table-responsive">
        <Table className="table no-margin"  noDataText="No bolts found !"  currentPage={boltsActivePage-1} itemsPerPage={pageSize}>
          <Thead>
            <Th column="boltId" title="The ID assigned to a the Component by the Topology. Click on the name to view the Component's page.">Id</Th>
            <Th column="executors" title="Executors are threads in a Worker process.">Executors</Th>
            <Th column="tasks" title="A Task is an instance of a Bolt or Spout. The number of Tasks is almost always equal to the number of Executors.">Tasks</Th>
            <Th column="emitted" title="The number of Tuples emitted.">Emitted</Th>
            <Th column="transferred" title="The number of Tuples emitted that sent to one or more bolts.">Transferred</Th>
            <Th column="capacity" title="If this is around 1.0, the corresponding Bolt is running as fast as it can, so you may want to increase the Bolt's parallelism. This is (number executed * average execute latency) / measurement time.">Capacity (last 10m)</Th>
            <Th column="executeLatency" title="The average time a Tuple spends in the execute method. The execute method may complete without sending an Ack for the tuple.">Execute Latency (ms)</Th>
            <Th column="executed" title="The number of incoming Tuples processed.">Executed</Th>
            <Th column="processLatency" title="The average time it takes to Ack a Tuple after it is first received.  Bolts that join, aggregate or batch may not Ack a tuple until a number of other Tuples have been received.">Process Latency (ms)</Th>
            <Th column="acked" title="The number of Tuples acknowledged by this Bolt.">Acked</Th>
            <Th column="failed" title="The number of tuples Failed by this Bolt.">Failed</Th>
            <Th column="errorHost" >Error Host:Port</Th>
            <Th column="lastError" >Last Error</Th>
            <Th column="errorTime" >Error Time</Th>
          </Thead>
          {
            _.map(blotfilteredEntities, (b,k) => {
              return(
                <Tr key={k}>
                  <Td column="boltId"><Link to={`/topology/${details.id}/component/${b.boltId}`}>{b.boltId}</Link></Td>
                  <Td column="executors">{b.executors}</Td>
                  <Td column="tasks">{b.tasks}</Td>
                  <Td column="emitted">{b.emitted}</Td>
                  <Td column="transferred">{b.transferred}</Td>
                  <Td column="capacity">{b.capacity}</Td>
                  <Td column="executeLatency">{b.executeLatency}</Td>
                  <Td column="executed">{b.executed}</Td>
                  <Td column="processLatency">{b.processLatency}</Td>
                  <Td column="acked">{b.acked}</Td>
                  <Td column="failed">{b.failed}</Td>
                  <Td column="errorHost">{b.errorHost !== '' ? b.errorHost+b.errorPort : '' }</Td>
                  <Td column="lastError">{b.lastError}</Td>
                  <Td column="errorTime">{b.errorTime !== null && b.errorTime !== 0 ? this.getDateFormat(b.errorTime) : '' }</Td>
                </Tr>
              );
            })
          }
        </Table>
        </div>
        {
          blotfilteredEntities.length !== 0
          ? <CommonPagination  {...boltPaginationObj} callBackFunction={this.callBackFunction.bind(this)} tableName="bolt"/>
          : ''
        }
      </Panel>
      <Panel expanded={expandConfig} collapsible header={configPanelHead} eventKey="5" onSelect={this.commonOnSelectFunction.bind(this,'expandConfig')}>
        <div className="input-group col-sm-4">
          <input type="text"  onKeyUp={this.handleFilter.bind(this,'topologyConfig')} className="form-control" placeholder="Search By Key" />
          <span className="input-group-btn">
          <button className="btn btn-primary" type="button"><i className="fa fa-search"></i></button>
          </span>
        </div>
        <Table className="table no-margin"  noDataText="No topology configuration found !"  currentPage={topologyActivePage-1} itemsPerPage={pageSize}>
          <Thead>
            <Th column="Key">Key</Th>
            <Th column="value">Value</Th>
          </Thead>
          {
            _.map(topologyfilteredEntities, (k,t) => {
              return(
                <Tr key={t}>
                  <Td column="Key">{k}</Td>
                  <Td column="value">{details.configuration[k]}</Td>
                </Tr>
              );
            })
          }
        </Table>
        {
          topologyfilteredEntities.length !== 0
          ? <CommonPagination  {...topologyPaginationObj} callBackFunction={this.callBackFunction.bind(this)} tableName="topologyConfig"/>
          : ''
        }
      </Panel>

      {/*Model start here*/}
      <Modal ref={"debugModelRef"} data-title="Do you really want to debug this topology ? If yes, please, specify sampling percentage."  data-resolve={this.handleModelAction.bind(this,'debugModelRef','save')} data-reject={this.handleModelAction.bind(this,'debugModelRef','hide')}>
        <input className="form-control" type="number" min={0} max={Number.MAX_SAFE_INTEGER} value={debugSimplePCT} onChange={this.inputTextChange.bind(this,'debugSimplePCT')}/>
      </Modal>

      <Modal ref={"killModelRef"} data-title="Are you sure you want to kill this topology ? If yes, please, specify wait time in seconds."  data-resolve={this.handleModelAction.bind(this,'killModelRef','save')} data-reject={this.handleModelAction.bind(this,'killModelRef','hide')}>
        <input className="form-control" type="number" min={0} max={Number.MAX_SAFE_INTEGER} value={killWaitTime} onChange={this.inputTextChange.bind(this,'killWaitTime')}/>
      </Modal>

      <Modal ref={"rebalanceModelRef"} data-title="Rebalance Topology"  data-resolve={this.handleModelAction.bind(this,'rebalanceModelRef','save')} data-reject={this.handleModelAction.bind(this,'rebalanceModelRef','hide')}>
        <RebalanceTopology ref={"rebalanceModal"} topologyId={details.id} spoutArr={details.spouts} boltArr={details.bolts} topologyExecutors={details.workersTotal}/>
      </Modal>

    </BaseContainer>);
  }
}
